- UI/src/app/dashboard/directives/widget.js
- UI/src/components/widgets/repo/config.js
fixed another bug, since the scm field is introduced in widgetConfig options to track the type of SCM (Currently Github/Subversion) all the existing dashboard needs to resave the properties of the Source Code widget.
> Fixed another bug with SourceControl widget

- UI/package.json
to eliminate npm warnings.
```
$ npm install
npm WARN package.json devops-dashboard@0.0.0 No repository field.
npm WARN package.json devops-dashboard@0.0.0 No license field.
```
> Add metadata to package.json

- Setup.md
- UI/src/components/widgets/codeanalysis/view.js
to prevent warnings when running `gulp serve`:
/Users/marca/dev/git-repos/Hygieia/UI/src/components/widgets/codeanalysis/view.js
line 80  col 14  Missing semicolon.
line 88  col 30  Missing semicolon.
⚠  2 warnings
> Add missing semicolons

- GitHubSourceCodeCollector/src/main/resources/logback.xml
- Setup.md
instead of buildcollector log file. The buildcollector log file had the
output of both the Jenkins collector and the GitHub collector
intermixed like this:
```
monkey@hygieia:/opt/hygieia/collectors$ tail -f buildcollector-2015-08-14.0.log
2015-08-14 00:21:00,002 INFO  c.c.d.collector.GitHubCollectorTask - ------------------------------
2015-08-14 00:21:00,002 INFO  c.c.d.collector.GitHubCollectorTask - Starting...
2015-08-14 00:21:00,002 INFO  c.c.d.collector.GitHubCollectorTask - ------------------------------
2015-08-14 00:21:00,080 INFO  c.c.d.collector.HudsonCollectorTask - Fetched jobs                0s
2015-08-14 00:21:00,129 INFO  c.c.d.collector.HudsonCollectorTask - New jobs           0        0s
2015-08-14 00:21:00,290 INFO  c.c.d.collector.HudsonCollectorTask - New builds …
```
> github-collector: Log to github-collector log file

- api/README.md
- api/pom.xml
the api layer can now be run in an embedded Jetty container by running the command
```bash
mvn jetty:run   -DPROP_FILE=<Path to dashboard.properties file>
```
> Added capabilities to run api in an embedded Jetty container

- BuildCollector/pom.xml
- CodeQualityCollector/pom.xml
- DeployCollector/pom.xml
- GitHubSourceCodeCollector/pom.xml
- JenkinsCucumberTestCollector/pom.xml
- JiraFeatureCollector/pom.xml
- SourceCodeCollector/pom.xml
- UI/pom.xml
- VersionOneFeatureCollector/pom.xml
- api/pom.xml
- common/pom.xml
- pom.xml
* Fixed POM's and added a release profile to be only used for releasing the binaries to Maven Central http://search.maven.org
* Fixed child parent relationship , spring-boot is extended now in parent pom and hence the collectors need not declare it as a parent.
* Fixed Embedded MongoDb test cases, they all run successfully now
* All the latest pull requests that have been merged are already released to Maven Central.
While we will be revisiting the strategy for versioning more appropriately after this.
> Modified Project Pom's for Maven Central release

- BuildCollector/README.md
- BuildCollector/src/main/java/com/capitalone/dashboard/collector/DefaultHudsonClient.java
- BuildCollector/src/main/java/com/capitalone/dashboard/collector/HudsonSettings.java
- BuildCollector/src/test/java/com/capitalone/dashboard/collector/DefaultHudsonClientTests.java
- sample.properties
Allows the Jenkins collector to connect to Jenkins servers that require authentication.
To enable basic auth, set the following properties:
```ini
jenkins.authRequired=true
jenkins.username=jenkins-username-goes-here
jenkins.apiKey=jenkins-apiKey-goes-here
```
> Add support for HTTP Basic Auth to Jenkins collector

- README.md
Adding a line about a code of conduct for Hygieia development. This is based on the publicly available TODO group's code of conduct.
> Add Hygieia code of conduct

- README.md
- Setup.md
- core/src/test/java/com/capitalone/dashboard/MarkdownTest.java
Absolute links in the markdown files didn't link correctly in branches and forks. Replaced with relative links and created junit that fails when an absolute link is included in a markdown file.
> replace absolute url links with relative links in markdown files

- .gitignore
- Setup.md
- core/src/main/java/com/capitalone/dashboard/model/Component.java
- core/src/test/java/com/capitalone/dashboard/repository/EmbeddedMongoDBRule.java
- core/src/test/java/com/capitalone/dashboard/repository/FeatureRepositoryTest.java
- jira-feature-collector/src/main/resources/jira-feature-collector.properties
- versionone-feature-collector/pom.xml
This enhancement enables the use and running of tests leveraging the embedded MongoDB test packages when an authenticated proxy is required.  This will also work with existing, non-authenticated proxy settings, as the logic for that option will run independent of the logic for authenticated proxies.
I also updated the Setup.md readme to include explicit instructions for how to configure both an authenticated and non-authenticated proxy.
> Enabled authenticated proxy configuration for embedded MongoDB tests

- UI/src/app/css/common.less
The overflow-x: scroll on the dashboard element that was introduced in Hygieia-2 caused charts to be rendered smaller than necessary under certain conditions.
> Fix for Chartist rendering issue

- UI/src/components/widgets/codeanalysis/view.js
reference #368 Code collector widget showing different tech debt value
In the current code I found 2 issues:
#1 the values in the DB returned in the rest call is in minutes, so we should be diving by 8*60 for 1d. (maybe older versions of sonar are using seconds if we find that is the case we may have to make this configurable)
#2 it appears the sonar ui is using floor() vs ceil() of the calculation, so I changed that to line up the UI's.
> Tech debt incorrect

- api/src/main/java/com/capitalone/dashboard/rest/DashboardController.java
- api/src/main/java/com/capitalone/dashboard/rest/ServiceController.java
- api/src/main/java/com/capitalone/dashboard/service/FeatureServiceImpl.java
- api/src/main/java/com/capitalone/dashboard/service/PipelineServiceImpl.java
- api/src/test/java/com/capitalone/dashboard/service/PipelineServiceTest.java
- core/src/main/java/com/capitalone/dashboard/model/Dashboard.java
- core/src/main/java/com/capitalone/dashboard/util/Encryption.java
- core/src/test/java/com/capitalone/dashboard/MarkdownTest.java
- jenkins-build-collector/src/test/java/com/capitalone/dashboard/collector/DefaultHudsonClientTests.java
- jenkins-cucumber-test-collector/src/test/java/com/capitalone/dashboard/collector/DefaultJenkinsClientTest.java
- subversion-scm-collector/src/main/java/com/capitalone/dashboard/collector/DefaultSubversionClient.java
reference #343 - Type safety Java Error in eclipse (10 cases)
There are a few cases left that need more research, the ones in the JIRA collectors broke tests when I fixed them.  The other 2 cases need more research on the proper resolution.
reference #352 - PMD Warnings - Avoid catching NullPointerException; consider removing the cause of the NPE - For now suppresed and added to TODO list
@tabladrum noted that these should be fixed, for today I suppressed them and marked them for the TODO list to cleanup, in this way we can monitor PMD more effectively.
> Eclipse  Type safety Java Error cleanup

- core/src/main/java/com/capitalone/dashboard/event/CommitEventListener.java
- core/src/test/java/com/capitalone/dashboard/event/CommitEventListenerTest.java
This PR is to fix a bug whereby commits can be orphaned in the commit stage of the product pipeline widget.
Here is the scenario:
1. A (team) dashboard exists with a configured SCM widget (using the Github webhook push method)
2. The same dashboard does **NOT** have a build widget configured
3. A new commit (call it commit A) is pushed to the Github repo
4. The build widget is then added to the team dashboard
5. A new product dashboard is created that references the team dashboard.
6. Commit A is displayed in the commit stage and never moves to subsequent stages.
This PR proposes to fix the bug by not adding commits to the pipeline of a team dashboard if there is no build widget configured.
> Fix for orphaned commits in commit stage of pipeline when no build configured

- Setup.md
- github-scm-collector/README.md
- jenkins-build-collector/README.md
- jira-feature-collector/README.md
- subversion-scm-collector/README.md
- udeploy-deployment-collector/README.md
- versionone-feature-collector/README.md
Hi
Please pull my changes are documentation for setting mongoDB database name is mentioned "dashboard" and "dashboard**db**" or "dashboard**b**" in different places (aka main or module level README.MD files). I fixed those so that other people won't face much issues.
Thanks.
Arun Sangal
> Fix mongoDB database name references as dashboard in all modules.

- sonar-codequality-collector/docker/sonar-codequality-properties-builder.sh
- sonar-codequality-collector/src/main/java/com/capitalone/dashboard/collector/DefaultSonarClient.java
- sonar-codequality-collector/src/main/java/com/capitalone/dashboard/collector/SonarSettings.java
This PR adds HTTP basic authentication support to the SonarQube collector.
> Add basic auth support to sonarqube collector

- UI/src/test-data/dashboard_detail.json
The changes to this file made on April 19 2016 cause JS errors in UI testing. You are unable to use the dashboard UI due to bower errors parsing invalid json. The bracket at the beginning and the comma + brace at the end need to be removed so that the UI runs while using gulp serve to test changes.
> Invalid json causing errors while testing

- pom.xml
Upgraded docker plugin to 0.4.10 to work with Docker Mac
> #638 - upgrade docker plugin to fix issue using it with docker mac 1.12

- chatops_collector.html
- plugin_webhook.html
- ui.html
Some of the images in the documentation do not appear because
the img src references the root context, which happens when the
documentation website is hosted on GitHub due to the project
prefix ("Hygieia").
This removes the root prefix ("/") for the affected images.
> Update image src to use path relative to current page

- core/src/main/java/com/capitalone/dashboard/collector/CollectorTask.java
Hi,
While trying to run the Jenkins build collector I've found that a place without proper spacing in the logs.
Example:
`2016-09-03 04:22:00,302 INFO  c.c.d.collector.CollectorTask - Error getting jobs for: http://10.100.68.2380s`
Note that the '0s' is not separated from the host at the end.
My change should make it so that there is always at least one space between the tokens.
> Fix log output bug - possible missing spaces between tokens

- Bamboo-build-collector/docker/bamboo-build-properties-builder.sh
- bitbucket-scm-collector/README.md
- bitbucket-scm-collector/docker/bitbucket-properties-builder.sh
- chat-ops-collector/docker/chat-ops-properties-builder.sh
- github-scm-collector/README.md
- github-scm-collector/docker/github-properties-builder.sh
- jenkins-build-collector/docker/jenkins-build-properties-builder.sh
- jenkins-cucumber-test-collector/docker/jenkins-cucumber-test-properties-builder.sh
- jira-feature-collector/docker/jira-properties-builder.sh
- sonar-codequality-collector/README.md
- sonar-codequality-collector/docker/sonar-codequality-properties-builder.sh
- subversion-scm-collector/README.md
- subversion-scm-collector/docker/subversion-properties-builder.sh
- udeploy-deployment-collector/README.md
- udeploy-deployment-collector/docker/udeploy-properties-builder.sh
- versionone-feature-collector/docker/versionone-properties-builder.sh
- xldeploy-deployment-collector/README.md
- xldeploy-deployment-collector/docker/xldeploy-properties-builder.sh
Almost all of the property generator scripts use a property named 'database' to specify what database to use. The code uses 'dbname'. Someone probably changed this property a while ago and forgot to update the property generator scripts. It has gone unnoticed because people probably have just used the default value for the database name.
This change fixes the property generator and property files to properly use 'dbname'
> Fix property generator scripts to generate 'dbname' property instead of 'database'

- api/src/main/java/com/capitalone/dashboard/model/PipelineResponseCommit.java
- api/src/main/java/com/capitalone/dashboard/service/CommitServiceImpl.java
- collectors/scm/bitbucket/src/main/java/com/capitalone/dashboard/collector/DefaultBitbucketCloudClient.java
- collectors/scm/bitbucket/src/main/java/com/capitalone/dashboard/collector/DefaultBitbucketServerClient.java
- collectors/scm/bitbucket/src/test/java/com/capitalone/dashboard/collector/DefaultBitbucketServerClientTest.java
- collectors/scm/github/src/main/java/com/capitalone/dashboard/collector/DefaultGitHubClient.java
- collectors/scm/github/src/test/java/com/capitalone/dashboard/collector/GitHubCollectorTaskTest.java
- core/src/main/java/com/capitalone/dashboard/event/CommitEventListener.java
- core/src/main/java/com/capitalone/dashboard/model/PipelineCommit.java
- core/src/main/java/com/capitalone/dashboard/model/SCM.java
Just as the title says. It will prove to be useful information in the future for some things I have planned. I wanted to get it in now so collectors can start filling up with the data.
Note that the parent revision data will only come from the commit collectors. SCM objects created by build collectors will not have the parent revision information (as it doesn't seem to be available in the api). Hence at present commits in the pipeline document for build and environments will not contain the parent scm revision number information.
> Add scm parent revision numbers to Commits

- collectors/feature/jira/src/test/java/com/capitalone/dashboard/client/project/ProjectDataClientImplTest.java
Fixes #840
Looks like this was introduced at or before: c01c9859ba3552244a43e86cdb209bebe0081349
I searched the whole project, so this should be the only occurrence.
> Fixed package in JIRA collector

- MAINTAINERS
- UI/src/app/dashboard/controllers/createDashboard.js
- UI/src/components/templates/capone.html
- UI/src/components/templates/capone.js
- UI/src/components/templates/caponechatops.html
- UI/src/components/templates/cloud.html
- UI/src/components/templates/cloud.js
- api/src/main/resources/application.properties
1. Code change for showing all the tabs moment the dashboard is created.
2. Ability to create standalone AWS cloud dashboard, This tab was earlier only visible if deploy widget was configured.
3. Modified Maintainers file to add new members
> Added template for standalone cloud widget

- UI/assembly/bin.xml
- UI/pom.xml
Used Maven assembly plugin to assemble UI project dist folder in tar gzip format
This will allow folks to consume each build artifact from Maven Central, with out need to build from source
> Change will generate gzip of UI project dist folder

- api/pom.xml
- api/src/main/java/com/capitalone/dashboard/rest/PingController.java
- api/src/main/resources/application.properties
- api/src/main/resources/version.properties
Spring boot tokenization works only for properties bundles inside the spring boot jar. To cater to this and preserve backwards compatibility.
- Introduced a new file called version.properties
- File gets updated by maven during build phase with current version.
- The property value is injected in the class requiring this.
> Bug Fix for Hygieia App version display

- getting_started.html
Just a couple minor updates to the getting started documentation.
- remove need for executing `package` goal in Maven since it already [executes at an earlier phase](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#Build_Lifecycle_Basics).
- fix the XML rendering for the Maven proxy configuration docs.
P.S. I've signed the contributor agreement.
> Some documentation updates

- collectors/scm/gitlab/README.md
- collectors/scm/gitlab/src/main/java/com/capitalone/dashboard/collecteur/GitlabSettings.java
- collectors/scm/gitlab/src/main/java/com/capitalone/dashboard/collecteur/GitlabUrlUtility.java
- collectors/scm/gitlab/src/test/java/com/capitalone/dashboard/collecteur/GitlabUrlUtilityTest.java
These changes allow users to choose which protocol and port to use when querying Gitlab's API.  Also added some more information in the Readme about running the collector and which properties are required.
Resolves #957
> Gitlab Custom Protocol/Port

- collectors/artifact/artifactory/src/main/resources/logback.xml
- collectors/build/bamboo/src/main/resources/logback.xml
- collectors/build/jenkins-cucumber/src/main/resources/logback.xml
- collectors/build/jenkins/src/main/resources/logback.xml
- collectors/build/sonar/src/main/resources/logback.xml
- collectors/deploy/udeploy/src/main/resources/logback.xml
- collectors/deploy/xldeploy/src/main/resources/logback.xml
- collectors/feature/jira/src/main/resources/logback.xml
- collectors/feature/versionone/src/main/resources/logback.xml
- collectors/scm/bitbucket/src/main/resources/logback.xml
- collectors/scm/github/src/main/resources/logback.xml
- collectors/scm/subversion/src/main/resources/logback.xml
When running in docker logs were getting lost because they were not being placed in the correct location (logs) that was mounted.
@pxk5958 
Fixes #988
> Fixed log file path for all collectors

- collectors/build/jenkins/README.md
- collectors/build/jenkins/docker/jenkins-build-properties-builder.sh
- collectors/build/jenkins/src/main/java/com/capitalone/dashboard/collector/DefaultHudsonClient.java
- collectors/build/jenkins/src/main/java/com/capitalone/dashboard/collector/HudsonSettings.java
- collectors/build/jenkins/src/test/java/com/capitalone/dashboard/collector/DefaultHudsonClientTests.java
- Adds paging to the jenkins collector. Page size defaults to 1000. Paging is necessary when there are a very large number of jobs as jenkins seems to choke if a rest response is too large.
@pxk5958
> Add paging to Jenkins collector

- UI/README.md
- UI/gulpfile.js
Since this has been the source of several issues, I think it best to disable browser-sync's [`ghostMode`](https://www.browsersync.io/docs/options/#option-ghostMode) feature, by default.
Ghost mode can be enabled by running `gulp serve:ghost-mode` if you require this functionality.
Resolves #1016
> Disabled browser-sync ghost mode, by default

- collectors/build/jenkins/docker/jenkins-build-properties-builder.sh
Problem: The Hygieia Jenkins Collector docker container fails on startup. The docker file runs a shell script to build property file. This shell script has an incorrectly declared if condition (was using parenthesis instead of brackets).
> correcting if condition on JENKINS_OP_CENTER

- collectors/scm/gitlab/src/main/resources/logback.xml
Adjusted the logback configuration on the gitlab-git-collector to keep it consistent with the other Hygieia collectors.
> Correct logback on gitlab-git-collector

- collectors/feature/versionone/docker/versionone-properties-builder.sh
When using docker to create a versionone collector, we found that there was no properties file was being created. This was due to a syntax error in the properties builder script when copying the values to the properties file. Once that file was created, the was no CRON being specified. CRON has been added to the versionone properties builder as well as the syntax errors being corrected.
> Fixed issues in version one properties builder shell file

- collectors/feature/gitlab/src/main/java/com/capitalone/dashboard/gitlab/GitlabUriUtility.java
- collectors/feature/gitlab/src/test/java/com/capitalone/dashboard/gitlab/GitlabUriUtilityTest.java
Currently the Gitlab feature collector accepts a Gitlab server with a corresponding port in the properties builder file. If the collector is started without a Gitlab port supplied, the port is processed as "", throwing a Number Format Exception. The logic in the URI builder has been updated to not include the port if it is an empty string.
> Gitlab feature collector - optional server port

- README.md
Some links and headers were broken on the readme, most likely caused by [Github's markdown changes](https://github.com/blog/2333-a-formal-spec-for-github-flavored-markdown)
> Fix readme markdown issues

- README.md
- Setup.md
- core/README.md
- core/create_collector.md
- features.md
- hygieia-jenkins-plugin/README.md
GitHub changed the way Markdown headings are parsed, so this change fixes it.
See [bryant1410/readmesfix](https://github.com/bryant1410/readmesfix) for more information.
Tackles bryant1410/readmesfix#1
> Fix broken headings in Markdown files

- collectors/feature/gitlab/README.md
- collectors/feature/gitlab/docker/gitlab-properties-builder.sh
- collectors/feature/gitlab/src/main/java/com/capitalone/dashboard/collector/FeatureSettings.java
- collectors/feature/gitlab/src/main/resources/logback.xml
- collectors/scm/gitlab/src/main/java/com/capitalone/dashboard/collector/GitlabSettings.java
- collectors/scm/gitlab/src/main/java/com/capitalone/dashboard/gitlab/DefaultGitlabGitClient.java
Updated the feature collector to function like the scm collector in being able to trust self signed certificates.  I also changed the scm collector to only set the property once, instead of on every request.  There is also a small logging file fix that puts the log files in a log folder like the other collectors.
> Gitlab Ignore Untrusted Certs/Log Location fix

- api/README.md
- api/docker/properties-builder.sh
- api/src/main/java/com/capitalone/dashboard/auth/AuthProperties.java
- api/src/main/java/com/capitalone/dashboard/config/WebSecurityConfig.java
Resolves #1385, #1383 .  Added a property for active directory url to make it more explicit as to what you are configuring.  The API also now handles null properties for the url so it can start even if not provided.  Would appreciate if someone could run this with active directory to make sure it works as intended.
> Active Directory Url Fix

- UI/src/components/widgets/deploy/config.html
- UI/src/components/widgets/deploy/config.js
- collectors/deploy/xldeploy/src/main/java/com/capitalone/dashboard/collector/DefaultXLDeployClient.java
- collectors/deploy/xldeploy/src/test/java/com/capitalone/dashboard/collector/DefaultXLDeployClientTest.java
- collectors/deploy/xldeploy/src/test/resources/com/capitalone/dashboard/collector/applicationHistory1.xml
This widget was skipped when changes were made to other widgets to convert them to use the uib-typeahead directive (#1049). This PR changes the deploy widget to use the typeahead mechanism. It works with or without the "aggregateServer" option. I also fixed an XLD bug while in here.
When aggregate servers is on it obtains data using the following algorithm:
```
/*
* Obtains deployment jobs using recursion when necessary. 
* 
* It is necessary to make additional calls when 'aggregateServers' is true since we need all like applications on different servers 
* to be available when saving our data. To do this we compare the last item in the list from our first paged call to all subsequent data.
* If the application name and id is the same then we keep the data in our list. Once we encounter …
```
> (Performance Fix) Change deploy widget to use uib-typeahead

- UI/src/app/dashboard/views/site.html
Looks like this got lost in a merge conflict.  Just hides the create button if you aren't logged in.
> Fix create dashboard button showing up when not logged in

- UI/README.md
- UI/gulpfile.js
How to modify Hygieia configuration to use a custom port number for the API server, instead of the default (`8080`). This pull request includes notes on how to modify `UI/gulpfile.js` to support custom API port.
> UI: comments and notes on how to use custom port number for API server

- api/README.md
- api/src/main/java/com/capitalone/dashboard/config/LoggingConfig.java
- api/src/main/java/com/capitalone/dashboard/logging/KeyValueLoggingCondition.java
- api/src/main/java/com/capitalone/dashboard/logging/KeyValueLoggingFilter.java
- api/src/test/java/com/capitalone/dashboard/logging/KeyValueLoggingConditionTest.java
- api/src/test/java/com/capitalone/dashboard/logging/KeyValueLoggingFilterTest.java
- core/src/main/java/com/capitalone/dashboard/model/KeyValueLog.java
This PR merely renames the splunk logging components to something that sounds a little more generic. While using the splunk product was the inspiration behind the components, we didn't want developers to feel like they needed splunk deployed in order to log in a key-value pair style.
@rob-miller-777
> Renamed Splunk Logging Components

- UI-tests/README.md
- UI-tests/src/main/resources/stories/delete_dashboard_test.story
- UI-tests/src/test/java/com/capitalone/dashboard/uitest/definitions/DeleteDashboardDefinitions.java
- UI-tests/src/test/java/com/capitalone/dashboard/uitest/pages/HomePage.java
- UI-tests/src/test/java/com/capitalone/dashboard/uitest/pages/LoginPage.java
- UI-tests/src/test/java/com/capitalone/dashboard/uitest/steps/UserSteps.java
I have made the following changes
* Fixes for the tests from PR1264
* Added story, step definition, page objects and test for delete dashboard
```Scenario: User deletes a dashboard
Using timeout for story delete_dashboard_test.story of 300 secs.
Given I am an authorized project stakeholder
And I am on the Hygieia home screen
When I delete a team dashboard
Then the dashboard 'DummyDashboard' should be deleted
```
* Updated README.md for `Executing Tests Without Docker Setup`
All Tests are passed without any issues
```Reports view generated with 4 stories (of which 0 pending) containing 4 scenarios (of which 0 pending)
Tests run: 28, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 38.06 sec - in com.capitalone.dashboard.uitest.UITestRunner
Results :
Tests run: 28, Failures: 0, Errors: 0, …
```
> Fixes for PR1264 & new test for Delete Dashboard

- collectors/build/jenkins/src/main/java/com/capitalone/dashboard/collector/DefaultHudsonClient.java
Add a simple log statement that gives the progress of Jenkins job retrieval. Useful for knowing the state of a job pull - sometimes on large instances Jenkins chokes (cause unknown) resulting in the pull taking a half hour.
Example:
> 2017-08-31 12:24:17,354 INFO  c.c.d.collector.DefaultHudsonClient - Fetching jobs 0/4185 pageSize 250...
> 2017-08-31 12:24:18,368 INFO  c.c.d.collector.DefaultHudsonClient - Fetching jobs 250/4185 pageSize 250...
> 2017-08-31 12:24:19,098 INFO  c.c.d.collector.DefaultHudsonClient - Fetching jobs 500/4185 pageSize 250...
> 2017-08-31 12:24:20,058 INFO  c.c.d.collector.DefaultHudsonClient - Fetching jobs 750/4185 pageSize 250...
> 2017-08-31 12:24:21,676 INFO  c.c.d.collector.DefaultHudsonClient - Fetching jobs 1000/4185 pageSize 250...
> 2017-08-31 …
> Add log to track progress of jenkins job retrieval.

- collectors/build/bamboo/pom.xml
- collectors/build/jenkins-codequality/pom.xml
Both the bamboo and jenkins codequality collectors are using the docker image name "hygieia-jenkins-build-collector". This causes the real hygieia jenkins build collector docker image to get overwritten.
Resolves #1690
> Fix incorrect docker image names #1690

- collectors/deploy/xldeploy/src/main/java/com/capitalone/dashboard/collector/DefaultXLDeployClient.java
XLD 6.x seems to default to returning json on a query where it used to default to returning XML. Add an accept header to make sure we get XML back.
> Fix accept header for xml to xld collector

- collectors/build/sonar/src/main/java/com/capitalone/dashboard/collector/SonarClientSelector.java
Fix for issue #1517 #1311  Sonarqube v6.0-v6.2 returning 404 
Changes : 
DefaultSonar6Client has sonar API URLs which  is supported only for sonar 6.3 and above. 
For sonar version 6.2 and below DefaultSonarClient should be used.
> Fix for sonar collector for v6.0-v6.2

- api-audit/src/main/java/com/capitalone/dashboard/ApiSettings.java
- api-audit/src/main/java/com/capitalone/dashboard/service/AuditServiceImpl.java
- api-audit/src/test/java/com/capitalone/dashboard/service/AuditServiceTest.java
- collectors/scm/github/src/main/java/com/capitalone/dashboard/collector/DefaultGitHubClient.java
- core/src/main/java/com/capitalone/dashboard/model/CommitStatus.java
- core/src/main/java/com/capitalone/dashboard/model/GitRequest.java
- core/src/main/java/com/capitalone/dashboard/model/Review.java
Tests peer review using either GitHub commit statuses or GitHub reviews. If the Hygieia API settings are populated with a list of peer review contexts then test the commit statuses.  When a commit status with a matching context is found, then use the state of the commit status to indicate peer review. If the Hygieia API settings do not have a peer review context then do not use the commit status.
When no peer review commit status is found then fallback to using GitHub Reviews. Check for at least one approved review. GitHub Reviews does not allow self-review. Closes #1735
> Approval management

- UI/src/app/dashboard/views/admin.html
The admin section was missing confirmation when attempting to delete dashboards, templates and api tokens. This PR adds the confirmation directive to all deletes on the admin page.
> Added confirmation directive to all deletes on admin page

- UI/docker/conf-builder.sh
This solves issue [#1856](https://github.com/capitalone/Hygieia/issues/1856). In the current state no matter what you attempt to set API_HOST to, you always get 'hygieia-api' as the hostname. In addition 127.0.0.1 is the current default which is rather useless as the api will never be reachable at this address.
The solution: remove the two export statements because they interfere with a user's ability to set the api hostname using ENV vars. Also change '127.0.0.1' to 'hygieia-api' since that hostname will be provided for you if you are using container linking or networking.
> UI conf-builder.sh to have sensible default for API_HOST

- api-audit/src/main/java/com/capitalone/dashboard/evaluator/CodeQualityEvaluator.java
This will prevent a dual audit status for the quality profile validation
as it currently returns an audit status of
**QUALITY_PROFILE_VALIDATION_AUDIT_NO_CHANGE** and
**QUALITY_PROFILE_VALIDATION_AUDIT_OK** even if there is no change in the
quality profile validation
@satishc1 @tabladrum
> Returns from function for no profile configuration change

- api-audit/src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluator.java
- api-audit/src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluatorLegacy.java
- api-audit/src/main/java/com/capitalone/dashboard/status/CodeReviewAuditStatus.java
- api/src/main/java/com/capitalone/dashboard/service/CollectorServiceImpl.java
- core/src/main/java/com/capitalone/dashboard/model/CollectorItem.java
Changes a couple of things:
1. Adds repo_not_configured and pending_data_collection statuses to codereviewaudit.
2. Doesn't clear out errors when the remoteUpdate api updates a collector item.
3. Changes the reset logic for a collector item where instead of clearing all errors, it only clears the oldest one so as to drop it below the threshold count.
> Modify error handling

- UI/src/components/widgets/codeanalysis/view.html
If no scan data is present in the db then the "View All" button on the Code Quality widget will set an empty href. In this case when you click on the button it will take you the home page since the Hygieia UI is a single page app. This PR uses ng-href instead which supports expressions. So now if there is no scan data then caWidget.reportUrl will evaluate to false and no href will be set.
> Code Quality Widget - Disable "View All" if no scan has been performed yet

- UI/Dockerfile
- UI/docker/Dockerfile
Related to issue #2089
I get a permission denied error from nginx when running the image. Clearing the site data or cookies it not sufficient. If I open a bash in the running image, I can see that the html folder is owned by nginx but all its files belong to root. Chowning them to nginx solves the problem.
> Chown in UI dockerfiles to change owner on nginx files

- api-audit/docker/properties-builder.sh
- collectors/artifact/artifactory/docker/properties-builder.sh
- collectors/build/bamboo/docker/properties-builder.sh
- collectors/build/jenkins-codequality/docker/properties-builder.sh
- collectors/build/jenkins-cucumber/docker/properties-builder.sh
- collectors/build/jenkins/docker/properties-builder.sh
- collectors/cmdb/hpsm/docker/properties-builder.sh
- collectors/deploy/udeploy/docker/properties-builder.sh
- collectors/deploy/xldeploy/docker/properties-builder.sh
- collectors/feature/gitlab/docker/properties-builder.sh
- collectors/feature/jira/docker/properties-builder.sh
- collectors/feature/versionone/docker/properties-builder.sh
- collectors/library-policy/nexus-iq-collector/docker/properties-builder.sh
- collectors/misc/chat-ops/docker/properties-builder.sh
- collectors/misc/score/docker/Dockerfile
- collectors/misc/score/docker/properties-builder.sh
- collectors/performance/appdynamics/docker/properties-builder.sh
- collectors/scm/bitbucket/docker/properties-builder.sh
- collectors/scm/github/docker/properties-builder.sh
- collectors/scm/gitlab/docker/properties-builder.sh
- collectors/scm/subversion/docker/properties-builder.sh
Some collectors have the correct values but most don't. I took the values from the DB setup script and modified all the properties-builder.sh to use them, so we don't have to provide those in the docker-compose.override.yml for each of the collectors.
> Set DB properties to the correct defaults in all collectors

- api-audit/src/main/java/com/capitalone/dashboard/evaluator/RegressionTestResultEvaluator.java
Fix for bug https://github.com/capitalone/Hygieia/issues/2101
Due to passing the wrong widgetName in getCollectorItems() for RegressionTestResultEvaluator, status is being displayed as `DASHBOARD_TEST_NOT_CONFIGURED` every time for AuditType: `Test` and the results are not being populated for audit API calls.
> RegressionTestResultEvaluator Bug Fix

- hygieia-jenkins-plugin/src/main/java/hygieia/builder/BuildBuilder.java
- hygieia-jenkins-plugin/src/main/java/hygieia/utils/HygieiaUtils.java
When using the Plugin for a multi branch pipeline, it was not easy to search for the jobs. Updating to store the path makes it easier to search for the jobs. @tabladrum @nireeshT 
Update:
If an issue is found with the job path then we return the job name.
> Update for plugin to store build path instead of name

- api/src/main/java/com/capitalone/dashboard/rest/DashboardController.java
- api/src/main/java/com/capitalone/dashboard/service/DashboardService.java
- api/src/main/java/com/capitalone/dashboard/service/DashboardServiceImpl.java
- api/src/test/java/com/capitalone/dashboard/rest/DashboardControllerTest.java
The renameDashboard API pulls all existing dashboards and then searches each one for a dashboard with the same title. The causes performance issues when there are a high number of dashboards.
Changes include:
Removed search logic and added logic to directly check the db for dashboards with an existing title.
Also, added null check
> Fix dashboard rename bug

- collectors/feature/rally/pom.xml
When executing `mvn docker:build` on root directory, we will meet an error:
> [INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building com.capitalone.dashboard:rally-collector 2.0.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- docker-maven-plugin:0.4.10:build (default-cli) @ rally-collector ---
[INFO] Copying /opt/Hygieia/collectors/feature/rally/target/rally-collector-2.0.5-SNAPSHOT.jar -> /opt/Hygieia/collectors/feature/rally/target/docker/rally-collector-2.0.5-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] --------------------------------------------------------------------- …
> Skip build docker for rally

- collectors/scm/github/src/main/java/com/capitalone/dashboard/collector/DefaultGitHubClient.java
Github's `Link` header values are URL Encoded. An example:
```
Key: Link
Value: <https://api.github.com/repositories/<some_repo>/commits?sha=refs%2Fheads%2Fmaster&since=2018-06-06T17%3A39Z&page=2>; rel="next", <https://api.github.com/repositories/<some_repo>/commits?sha=refs%2Fheads%2Fmaster&since=2018-06-06T17%3A39Z&page=2>; rel="last"
```
The client as written is incapable of correctly following an encoded link and results in a 404 Not Found error.
I suspect this error is what has been reported here and there already but hasn't been reproduced -- I spent the day spelunking this project's Issue history and noticed several issues similar to what I observed today.
I confirmed this resolution by crafting a small test I could step through in my IDE, that looked like:
```
@Test
public void …
```
> Bugfix: Github Collector Client chokes on URL-encoded `Link` header values.

- collectors/build/sonar/src/main/java/com/capitalone/dashboard/collector/DefaultSonar6Client.java
Per the docs for SonarQube at https://docs.sonarqube.org/display/DEV/Web+API when using token based authentication then the token goes into the username part, followed by a colon and empty password.
The current code base does not allow a null password, it is expecting both a username and password, this PR corrects that.
See https://docs.sonarqube.org/display/DEV/Web+API
> Allow tokens to be used for SonarQube authentication

- UI/src/components/widgets/codeanalysis/view.js
When there is no data the console will not stop through errors added this if check to fix the undefined value.
> Fix for the unlimited amount of console errors For Open Source Widget

- api/src/main/java/com/capitalone/dashboard/service/DashboardRemoteServiceImpl.java
- api/src/test/java/com/capitalone/dashboard/fixture/DashboardFixture.java
- api/src/test/java/com/capitalone/dashboard/service/DashboardRemoteServiceTest.java
Changes to all dashboards to be updated based on the provided Business Service and Business Application and not just the title. 
With old logic if a Dashboard exist with a Business Service and Business Application but was being updated via the API and the Titles didn't match, the update would fail. Dashboards with a Business Service and Business Application combination are unique so the dashboard should be updated, if they match, no matter what the title is.
> Remote dashboard create and update enhancement 

- api/src/main/java/com/capitalone/dashboard/config/WebSecurityConfig.java
- api/src/main/java/com/capitalone/dashboard/rest/BuildController.java
- api/src/main/java/com/capitalone/dashboard/rest/CodeQualityController.java
- api/src/main/java/com/capitalone/dashboard/rest/DeployController.java
- api/src/main/java/com/capitalone/dashboard/rest/TestResultController.java
- api/src/main/java/com/capitalone/dashboard/service/BuildService.java
- api/src/main/java/com/capitalone/dashboard/service/BuildServiceImpl.java
- api/src/main/java/com/capitalone/dashboard/service/CodeQualityService.java
- api/src/main/java/com/capitalone/dashboard/service/CodeQualityServiceImpl.java
- api/src/main/java/com/capitalone/dashboard/service/DeployService.java
- api/src/main/java/com/capitalone/dashboard/service/DeployServiceImpl.java
- api/src/main/java/com/capitalone/dashboard/service/TestResultService.java
- api/src/main/java/com/capitalone/dashboard/service/TestResultServiceImpl.java
- api/src/test/java/com/capitalone/dashboard/rest/BuildControllerTest.java
- api/src/test/java/com/capitalone/dashboard/rest/CodeQualityControllerTest.java
- api/src/test/java/com/capitalone/dashboard/rest/DeployControllerTest.java
- api/src/test/java/com/capitalone/dashboard/service/BuildServiceTest.java
- api/src/test/java/com/capitalone/dashboard/service/CodeQualityServiceTest.java
- api/src/test/java/com/capitalone/dashboard/service/DeployServiceTest.java
- api/src/test/java/com/capitalone/dashboard/service/TestResultServiceTest.java
- hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/DefaultHygieiaService.java
- hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/HygieiaGlobalListener.java
- hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/HygieiaGlobalListenerTest.java
- Build, Code Quality, Test and Deploy POST end points now return document id and collector item id. This potentially breaks older clients. Added /v2/ rest endpoints for these keeping the old one as is. 
- Minor update to Jenkins plugin: If build publish fails, do not try to publish anything else as the build objectID is necessary to relate other information.
> Backward compatibility for POST endpoints. Jenkins plugin update: 

- .travis.yml
.m2 cache caches failed attempts to reach maven central which stops subsequent builds from pulling files even if they now exist. This does not allow us to rerun builds in a timely manner if we know the artifact is now there.
> Remove .m2 from cache

- .travis.yml
This changes the behavior for merges to master. Currently builds are failing because the build triggered by merges to master attempt to deploy snapshots, but if the version in the pom is not a SNAPSHOT then it'll try to deploy a release and will fail due to insufficient permissions to overwrite an existing version. Now, on merge to master no deploy will be attempted.
> Don't deploy on master

- pages/hygieia/setup.md
The core needs to be downloaded separately and built in order to run the project.
> Adding core download information

- collectors/build/sonar/src/main/java/com/capitalone/dashboard/collector/DefaultSonar6Client.java
Fix for Sonar api limit to 10000 results. Added max pages to 20 of page size 500. 
This serves as a temporary work around to get max of 10000 records. 
TODO : Add more filters to pull all the projects from Sonar.
> Fix for Sonar api limit to 10000 results. Added max pages to 20.

- api/src/main/java/com/capitalone/dashboard/service/DashboardRemoteServiceImpl.java
- api/src/test/java/com/capitalone/dashboard/config/ApiTestConfig.java
- api/src/test/java/com/capitalone/dashboard/config/FongoConfig.java
- api/src/test/java/com/capitalone/dashboard/service/DashboardRemoteServiceTest.java
- api/src/test/java/com/capitalone/dashboard/util/TestUtil.java
- api/src/test/resources/collector_items/items.json
- api/src/test/resources/collectors/coll.json
- api/src/test/resources/component/component.json
- api/src/test/resources/dashboard/dashboard.json
- api/src/test/resources/dashboardRemoteRequests/0-Remote-Update-Repo.json
- api/src/test/resources/dashboardRemoteRequests/Remote-Request-Base.json
- api/src/test/resources/userInfo/user.json
1. 1. This update fixes an issue when calling the remote dashboard Update API, if a user has a dashboard with the Quality widget configured and only passes and update for sonar, it will clear our the other 3 widgets (Tests, Open Source, Security Scan). 
2.  Adds Fongo testing to get a more fine grain test for the remoteUpdate/Create API.
> Fixes widget wipe out issue when calling remote dashboard Update API

- api/config.env
- api/docker/properties-builder.sh
Following issues have been fixed for API docker containers:
1. Added dbhost property to enable DB hosted outside docker.
2. Fixed documentation link for GitHub private repo.
3.Added example docker environment file.
4. Added documentation on Hygieia wiki on how to run API Docker container with environment file.
> Fix for docker api container DB hosted outside docker environment.

- pom.xml
Looks like you're not using any error-checking in your Java build. This pull requests adds a static analysis tool, [Error Prone](http://errorprone.info), created by Google to find common errors in Java code. For example, running ```mvn compile``` on the following code:
```java
public boolean validate(String s) {
return s == this.username;
}
```
would identify this error:
```
[ERROR] src/main/java/HelloWorld.java:[17,17] error: [StringEquality] String comparison using reference equality instead of value equality
[ERROR]     (see https://errorprone.info/bugpattern/StringEquality)
```
If you think you might want to try out this plugin, you can just merge this pull request. Please feel free to add any comments below explaining why you did or did not find this recommendation useful.
> Error Prone Static Analysis Tool

- api/src/main/java/com/capitalone/dashboard/service/CodeQualityServiceImpl.java
Resolves #2577
with help of pull request to [hygieia-core PR-#36](https://github.com/Hygieia/hygieia-core/pull/36)
* When creating code quality collector the name is set to the specified in the `CodeQualityCreateRequest#toolName`.
* If it is not specified, then the default tool name `Sonar` will be kept (to tally with existing collectors)
> CodeQuality Collector name can be set using create request

- hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/workflow/HygieiaTestPublishStep.java
With out this change api throws error because it can't covert the buildId value passed in.
> Fix issue when trying to publish test results

- collectors/feature/jira/src/main/java/com/capitalone/dashboard/collector/DefaultJiraClient.java
- collectors/feature/jira/src/main/java/com/capitalone/dashboard/collector/FeatureSettings.java
- collectors/feature/jira/src/test/java/com/capitalone/dashboard/config/TestConfig.java
I was having issues with getting all the different story types with the only one story id from my companies jira instance. So I added the capability for multiple story ids.
> Jira: Add in capability for multiple story ids

- collectors/scm/github-graphql/pom.xml
- collectors/scm/github-graphql/src/main/java/com/capitalone/dashboard/collector/DefaultGitHubClient.java
- collectors/scm/github-graphql/src/test/java/com/capitalone/dashboard/collector/DefaultGitHubClientTest.java
When an error is thrown for a GraphQL query, the errors are returned in the JSON response.  The errors are checked for "NOT_FOUND", which means that the repo could have been redirected.  A REST call is made to the original repo to look for the new repo url.
> Graphql collector fix for redirected repos

- collectors/feature/jira/src/main/java/com/capitalone/dashboard/collector/DefaultJiraClient.java
- collectors/feature/jira/src/main/java/com/capitalone/dashboard/collector/FeatureCollectorTask.java
- collectors/feature/jira/src/main/java/com/capitalone/dashboard/collector/JiraClient.java
- collectors/feature/jira/src/test/java/com/capitalone/dashboard/collector/DefaultJiraClientTest.java
- collectors/feature/jira/src/test/java/com/capitalone/dashboard/collector/FeatureCollectorTaskTest.java
- collectors/feature/jira/src/test/java/com/capitalone/dashboard/config/TestConfig.java
- collectors/feature/jira/src/test/resources/response/issuetype.json
Removes the requirement for the properties to use:
```
feature.jiraStoryIds[0]=
feature.jiraEpicId=
```
Now the collector only relies on `feature.jiraIssueTypeNames=` to have the issue type names in a comma separated string as usual.
> closes #2892 - Fix for Jira Collector requiring manual insert for Issue Type IDs

- collectors/build/bamboo/docker/properties-builder.sh
- collectors/build/bamboo/src/main/java/com/capitalone/dashboard/collector/BambooSettings.java
- collectors/build/bamboo/src/main/java/com/capitalone/dashboard/collector/DefaultBambooClient.java
- Uses JENKINS_MAX_PLANS environment variable
- Mapped to bamboo.maxPlans in properties-builder.sh
- Defaults to (current) 2000 if not specified.
> fix: 2609 - Configurable max-result URL variable

- collectors/scm/github/src/main/java/com/capitalone/dashboard/collector/DefaultGitHubClient.java
Fixes - Github Collector tries to decrypt the Personal Access Token passed from the settings.
> Github Collector - Removes api key decryption requirement from token passed via settings

- api/src/main/java/com/capitalone/dashboard/service/CollectorServiceImpl.java
Look up tries to use the collectorItemId which causes a null pointer when enabling the score widget and configuring the Feature widget. Updated to look up by the collectorId.
> Fixes: #2929

- collectors/build/jenkins/src/main/java/com/capitalone/dashboard/collector/HudsonCollectorTask.java
- collectors/build/jenkins/src/main/java/com/capitalone/dashboard/collector/HudsonSettings.java
On the first execution of the Jenkins collector there is a NPE that prevents the collector document for Jenkins from being created. This prevents the General Configuration page from showing the Jenkins configuration.
NPE is avoided by initializing the offending fields in the HudsonSettings class.
> Fix NPE breaking admin page config

- collectors/scm/bitbucket/src/main/java/com/capitalone/dashboard/collector/SCMHttpRestClient.java
- collectors/scm/bitbucket/src/test/java/com/capitalone/dashboard/collector/SCMHttpRestClientTest.java
This PR fixes defect for incorrect decryption of credentials for global credentials for Bitbucket.
There was no unit test covering this scenario so I have added a unit test as well.
cc: @Sbrenthughes @rvema
> Fix - correctly decrypt password when handling default credentials

- mongosrc.js
The script is wrong. First it says `use dashboarddb` but then uses dashboard as db name...
> fix database name in createUser

- collectors/misc/score/src/main/java/com/capitalone/dashboard/ScoreSettingsService.java
- collectors/misc/score/src/main/java/com/capitalone/dashboard/widget/GithubScmWidgetScore.java
- collectors/misc/score/src/test/java/com/capitalone/dashboard/widget/GithubScmWidgetScoreTest.java
you can see at GithubScmWidgetScore.java method getPercentCoverageForDays that the score is actually Days with commits.
fix #3011
> Fix github score category name

- pages/hygieia/api/api.md
Having two apiToken strings is confusing. authHeader already has apiToken in it
> API Documentation: Remove duplicate token string in authorization header

- UI/src/app/dashboard/services/authInterceptor.js
Users are forced to login page when api throws 500 errors. Fixing so that they are redirected to login page only when they see 401 or 403.
> Fix the issues with user logins

- UI/gulpfile.js
so we're not searching all node modules for all fonts. This really increases build speed.
Raised this in isolation to #3142 in case that PR is too large.
Address: #3144
> only create fonts from awesome-font

- UI/src/components/widgets/repo/view.js
Fix pull request count for a day, seven day and fourteen days. A pull request count should be aggregated.
resolves : https://github.com/Hygieia/Hygieia/issues/3181
The logic for commits count in repo widget is correct but it is incorrect for PR and issues -
https://github.com/Hygieia/Hygieia/blob/8f14d527dfba42fae5abe65a17224754b887d4e6/UI/src/components/widgets/repo/view.js#L184-L207
If an issue is included in 7 days count then it should be included in 14 days count as well. So `else if` block should be replaced with `if` block,
https://github.com/Hygieia/Hygieia/blob/master/UI/src/components/widgets/repo/view.js#L297-L312
This PR fixes this issue by changing `else if` to `if` block.
> Fix pull request count for repo widget

- _data/sidebars/hygieia_sidebar.yml
- pages/hygieia/api/api.md
- pages/hygieia/collectors/collectors.md
- pages/hygieia/newUI.md
Documentation refresh for instruction guide. 
Switched around sidebar and created direct links to the github readme pages.  Collectors, API and Audit API are in the same category under Components.
> Documentation upgrades to link directly to github pages.  

- pages/hygieia/newUI.md
This PR moves the UI setup in the readme of the archived [Hygieia/UI](https://github.com/hygieia/UI) to gh-pages and replaces the links in the [current documentation here](https://hygieia.github.io/hygieia/newUI.html)
> UI setup readme move to gh-pages
