UI/src/index.html

originally said "Test Dashboard"

updated index.html file to say "Hygieia Dashboard" on the title

---

JiraFeatureCollector/pom.xml
VersionOneFeatureCollector/pom.xml

updated jira dependencies to match that of contents in HEAD of artifact prior to official public release (fixed jira transient dependency issue)

Fixed jira transient dependency issue

---

README.md

the pronunciation was wrong - went with the pronunciation from eWeek

updated Hygieia pronunciation

---

DeployCollector/src/main/java/com/capitalone/dashboard/collector/DefaultUDeployClient.java

Moved the UDeployEnvResCompData object creation in the inner loop to create correct number of env-component objects.

Corrected logic to create environment-component correctly.

---

DeployCollector/src/main/java/com/capitalone/dashboard/collector/DefaultUDeployClient.java

Found the issue with some empty deploy jobs in uDeploy.

Null pointer check to handle some badly formed json response.

---

DeployCollector/src/main/java/com/capitalone/dashboard/collector/UDeployCollectorTask.java

For empty dashboard components, a NPE is thrown. Modified code to handle that situation.

NPE check for empty dashboard components.

---

DeployCollector/src/main/java/com/capitalone/dashboard/collector/UDeployCollectorTask.java
GitHubSourceCodeCollector/src/main/java/com/capitalone/dashboard/collector/DefaultGitHubClient.java

Support for github.com. Still will not support access behind proxy.

---

common/src/main/java/com/capitalone/dashboard/collector/CollectorTask.java
common/src/test/java/com/capitalone/dashboard/repository/CollectorTaskTests.java

Correcly update collector collection when properties file is updated.

---

api/src/main/java/com/capitalone/dashboard/service/EncryptionServiceImpl.java
api/src/test/java/com/capitalone/dashboard/config/TestConfig.java

Missing Bean in TestConfig resulting in build failure.

Added new Bean in TestConfig.

---

BuildCollector/README.md
CodeQualityCollector/README.md
DeployCollector/README.md
JenkinsCucumberTestCollector/README.md
JiraFeatureCollector/README.md
SourceCodeCollector/README.md
VersionOneFeatureCollector/README.md
api/README.md

Changed Readme's to make all database names to dashboarddb

---

Setup.md
UI/src/app/chartist/plugins/pointHalo.js
UI/src/app/chartist/plugins/tooltip.js

Enclose expression in parentheses as recommended at
http://stackoverflow.com/questions/8875878/javascript-instanceof-if-statement
Fixes these warnings on startup:
/Users/marca/dev/git-repos/Hygieia/UI/src/app/chartist/plugins/pointHalo.js
line 13  col 17  Confusing use of '!'.
⚠  1 warning
/Users/marca/dev/git-repos/Hygieia/UI/src/app/chartist/plugins/tooltip.js
line 19  col 17  Confusing use of '!'.
line 19  col 52  Confusing use of '!'.

Fix incorrect usage of ! with instanceof

---

Setup.md

https://github.com/msabramo/Hygieia/blob/patch-1/Setup.md

Setup.md: A few tweaks

---

JenkinsCucumberTestCollector/build.gradle
Setup.md
build.gradle
release.md
settings.gradle

Added JenkinsCucumber Collector & updated docs

---

JiraFeatureCollector/src/main/java/com/capitalone/dashboard/client/project/ProjectDataClientImpl.java
JiraFeatureCollector/src/main/java/com/capitalone/dashboard/client/story/StoryDataClientImpl.java
JiraFeatureCollector/src/main/java/com/capitalone/dashboard/client/team/TeamDataClientImpl.java
JiraFeatureCollector/src/main/java/com/capitalone/dashboard/datafactory/jira/JiraDataFactoryImpl.java
JiraFeatureCollector/src/main/java/com/capitalone/dashboard/datafactory/jira/sdk/connector/BaseConnectionImpl.java
JiraFeatureCollector/src/main/java/com/capitalone/dashboard/datafactory/jira/sdk/connector/GetResponseBuilderImpl.java

This was stuff that I added while trying to figure out why the `JiraFeatureCollector` wasn't working for me last night.
Cc: @sudarkoff, @aconrad

Add more debug logging to JiraFeatureCollector

---

BuildCollector/build.gradle
CodeQualityCollector/build.gradle
DeployCollector/build.gradle
GitHubSourceCodeCollector/build.gradle
JiraFeatureCollector/build.gradle
SourceCodeCollector/build.gradle
VersionOneFeatureCollector/build.gradle
api/build.gradle
build.gradle
common/build.gradle
common/src/test/java/com/capitalone/dashboard/util/EncryptionTests.java
gradle/wrapper/gradle-wrapper.properties

workaround transitive dependency issue from json-simple: https://code.google.com/p/json-simple/issues/detail?id=91

make sure to exclude junit from json-simple 

---

UI/pom.xml

We will create a separate goal later

Removed auto start of UI from UI pom.xml

---

JenkinsCucumberTestCollector/src/main/java/com/capitalone/dashboard/collector/DefaultJenkinsClient.java
JenkinsCucumberTestCollector/src/main/java/com/capitalone/dashboard/collector/JenkinsCucumberTestCollectorTask.java
JenkinsCucumberTestCollector/src/main/java/com/capitalone/dashboard/collector/JenkinsSettings.java

Changes:
1. Added clean up method
2. Fetch only jobs that have cucumber test data.

Added cleanup method. Also, only fetch jenkins job that have cucumber

---

CodeQualityCollector/README.md

updated Sample application.properties file so all Sonar metrics are included

updated Sonar Metrics for Sample application.properties file

---

CloudCollector/pom.xml
CloudCollector/src/main/java/com/capitalone/dashboard/collector/AWSCloudCollector.java
CloudCollector/src/main/java/com/capitalone/dashboard/collector/AWSCloudCollectorTask.java
CloudCollector/src/main/java/com/capitalone/dashboard/collector/AWSCloudSettings.java
CloudCollector/src/main/java/com/capitalone/dashboard/collector/DefaultAWSCloudClient.java
CloudCollector/src/main/java/com/capitalone/dashboard/model/AWSConfig.java
CloudCollector/src/main/java/com/capitalone/dashboard/repository/AWSConfigRepository.java
common/pom.xml
common/src/main/java/com/capitalone/dashboard/model/CloudAggregatedData.java
common/src/main/java/com/capitalone/dashboard/model/CloudCpuUtilization.java
common/src/main/java/com/capitalone/dashboard/model/CloudRawData.java
common/src/main/java/com/capitalone/dashboard/model/CollectorType.java
common/src/main/java/com/capitalone/dashboard/repository/CloudAggregatedDataRepository.java
common/src/main/java/com/capitalone/dashboard/repository/CloudRawDataRepository.java

Major refactoring

---

JiraFeatureCollector/pom.xml
VersionOneFeatureCollector/pom.xml

fixed scope of junit dependency

scope should be test, not testing

---

api/src/main/java/com/capitalone/dashboard/rest/AuthenticationController.java
api/src/main/java/com/capitalone/dashboard/service/AuthenticationServiceImpl.java
common/src/main/java/com/capitalone/dashboard/model/Authentication.java
common/src/main/java/com/capitalone/dashboard/repository/AuthenticationRepository.java
common/src/test/java/com/capitalone/dashboard/repository/AuthenticationRepositoryTest.java
common/src/test/java/com/capitalone/dashboard/repository/DashboardCreateTests.java

Looking at the Authentication Collection, it turns out that the usernames were not unique. Created a fix to have unique usernames, and also added a test for it. removed the findByUsernameAndPassword method in AuthenticationRepository because its redundant now with findByUsername and unique usernames

Username was not unique

---

GitHubSourceCodeCollector/src/main/java/com/capitalone/dashboard/model/GitHubRepo.java

Fixed a bug in GithubCollector

fixed a bug in github collector

---

api/src/main/java/com/capitalone/dashboard/rest/AuthenticationController.java
api/src/main/java/com/capitalone/dashboard/service/AuthenticationServiceImpl.java
api/src/test/java/com/capitalone/dashboard/service/AuthenticationServiceTest.java
common/src/main/java/com/capitalone/dashboard/model/Authentication.java
common/src/test/java/com/capitalone/dashboard/repository/AuthenticationRepositoryTest.java

addresses issue #78 - this will now store user passwords hashed in sha512, which is not perfect, but better than plain text.

hash user passwords

---

README.md

Updating link to point to the version on CapitalOne.io

Changing the Code of Conduct URL

---

.gitignore
UI/pom.xml
UI/src/app/index.less
UI/src/index.html
api/pom.xml
core/pom.xml
core/src/main/java/com/capitalone/dashboard/collector/CollectorTask.java
core/src/main/java/com/capitalone/dashboard/config/MongoConfig.java
github-scm-collector/pom.xml
jenkins-build-collector/pom.xml
jenkins-cucumber-test-collector/pom.xml
jira-feature-collector/pom.xml
pom.xml
rev-version.sh
sonar-codequality-collector/pom.xml
subversion-scm-collector/pom.xml
udeploy-deployment-collector/pom.xml
versionone-feature-collector/pom.xml

fixed version to be greater than the largest released component (versionone was 1.3.0)
added more logging, added version change script & cleaned up poms

fixed versioning in the poms

---

UI/src/index.html

this was causing an issue in packaging..

added missing directive for dist index build

---

core/src/main/java/com/capitalone/dashboard/model/Authentication.java
core/src/test/java/com/capitalone/dashboard/repository/AuthenticationRepositoryTest.java

@tabladrum code review this fix plz.

corrected bug in passwd verification

---

core/src/main/java/com/capitalone/dashboard/repository/FeatureRepository.java
jira-feature-collector/src/main/java/com/capitalone/dashboard/repository/FeatureRepository.java
jira-feature-collector/src/main/java/com/capitalone/dashboard/repository/ProjectRepository.java
jira-feature-collector/src/main/java/com/capitalone/dashboard/repository/TeamRepository.java

I had to remove $query due to the redundancy

fix $query bug

---

udeploy-deployment-collector/src/main/java/com/capitalone/dashboard/collector/DefaultUDeployClient.java
udeploy-deployment-collector/src/main/java/com/capitalone/dashboard/collector/UDeployClient.java
udeploy-deployment-collector/src/main/java/com/capitalone/dashboard/collector/UDeployCollectorTask.java
udeploy-deployment-collector/src/test/java/com/capitalone/dashboard/collector/DefaultUDeployClientTest.java
udeploy-deployment-collector/src/test/resources/com/capitalone/dashboard/collector/fileTree1.json
udeploy-deployment-collector/src/test/resources/com/capitalone/dashboard/collector/fileTree2.json
udeploy-deployment-collector/src/test/resources/com/capitalone/dashboard/collector/noncompliance.json
udeploy-deployment-collector/src/test/resources/com/capitalone/dashboard/collector/resources.json

Component name is not good enough for tracking actual artifact. Other refactors.

Collect name of physical artifact that was deployed. 

---

jira-feature-collector/pom.xml
jira-feature-collector/src/main/java/com/capitalone/dashboard/client/project/ProjectDataClientSetupImpl.java
jira-feature-collector/src/main/java/com/capitalone/dashboard/client/story/FeatureDataClientSetupImpl.java
jira-feature-collector/src/main/java/com/capitalone/dashboard/client/team/TeamDataClientSetupImpl.java
jira-feature-collector/src/main/java/com/capitalone/dashboard/datafactory/jira/JiraDataFactoryImpl.java
jira-feature-collector/src/main/java/com/capitalone/dashboard/util/ClientUtil.java
jira-feature-collector/src/main/resources/jira-feature-collector.properties
jira-feature-collector/src/test/java/com/capitalone/dashboard/datafactory/jira/JiraDataFactoryImplTest.java

As mentioned by user @oshingc, there is a bug in the proxy / auth proxy string validation with the Jira collector that needs to be resolved.  If a user has not set a proxy, but their property file has the proxy / auth proxy props set as blank, or not there at all, the tool will currently throw a URI syntax or null pointer exception, as indicated in the following issue:  https://github.com/capitalone/Hygieia/issues/292
This has now been fixed.  Please validate and merge as soon as possible.  I have also wrote additional test cases to cover these scenarios for Jira connections.

Fixed based on proxy issue #292

---

UI/bower.json
UI/src/app/css/common.less
UI/src/components/widgets/product/product-mixins.less
UI/src/components/widgets/product/product.less
UI/src/components/widgets/product/quality-details/quality-details.html
UI/src/components/widgets/product/quality-details/quality-details.less
UI/src/components/widgets/product/quality-details/qualityDetails.js
UI/src/components/widgets/product/view.html
UI/src/components/widgets/product/view.js

start on quality details

---

jira-feature-collector/README.md
jira-feature-collector/pom.xml
jira-feature-collector/src/main/java/com/capitalone/dashboard/client/project/ProjectDataClientImpl.java
jira-feature-collector/src/main/java/com/capitalone/dashboard/client/project/ProjectDataClientSetupImpl.java
jira-feature-collector/src/main/java/com/capitalone/dashboard/client/story/FeatureDataClientSetupImpl.java
jira-feature-collector/src/main/java/com/capitalone/dashboard/client/story/StoryDataClientImpl.java
jira-feature-collector/src/main/java/com/capitalone/dashboard/client/team/TeamDataClientImpl.java
jira-feature-collector/src/main/java/com/capitalone/dashboard/client/team/TeamDataClientSetupImpl.java
jira-feature-collector/src/main/java/com/capitalone/dashboard/datafactory/jira/JiraDataFactoryImpl.java
jira-feature-collector/src/main/java/com/capitalone/dashboard/util/ClientUtil.java
jira-feature-collector/src/main/resources/jira-feature-collector.properties
jira-feature-collector/src/test/java/com/capitalone/dashboard/datafactory/jira/JiraDataFactoryImplTest.java

Because of issues with previous pull request reverted https://github.com/capitalone/Hygieia/pull/318 with upstream merge removing unexpected content related to Docker, this push will bring in updated feature collector content without removing Docker content.  Please let me know if any files need to be manually added or merged from the Docker pull content.
@tabladrum , please validate and re-merge to master.

Updated Feature collectors manually with upstream modifications included

---

UI/src/components/widgets/chatops/config.js
UI/src/components/widgets/chatops/view.js
UI/src/components/widgets/codeanalysis/config.html
UI/src/components/widgets/codeanalysis/config.js
UI/src/components/widgets/product/directives/directives.js
UI/src/components/widgets/repo/config.js
api/src/main/java/com/capitalone/dashboard/service/CodeQualityServiceImpl.java
hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/ActiveNotifier.java

1. Display job nice names in the drop down. 
2. Fix jenkins plugin's sonar data publish.
3. Remove extra console.log.

Handling NiceNames in Sonar job dropdown. Misc Fixes

---

UI/pom.xml

Skip=False flag was missing, got lost in the merges someplace. (did research where, just added it to unblock everyone.
@tabladrum  - can you merge this to unblock @stlouisweb

Reference #359 - Fixed Docker build

---

UI/src/components/widgets/codeanalysis/view.js

Reverts capitalone/Hygieia#375

Revert "Tech debt incorrect"

---

README.md
Setup.md
UI/README.md
api/README.md
core/README.md
hygieia-jenkins-plugin/README.md
media/README.md

Capital One is applying for trademark.

Update the project name with service mark in all the md file

---

api/pom.xml

Caution: Reformatting caused diff unreadable. Here is the only change
<dependency>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-actuator</artifactId>
</dependency>

Added Spring Actuator to allow API monitoring.

---

UI/src/components/templates/caponechatops.html
hygieia-jenkins-plugin/pom.xml
hygieia-jenkins-plugin/src/main/java/hygieia/builder/ArtifactBuilder.java
hygieia-jenkins-plugin/src/main/java/hygieia/builder/CucumberTestBuilder.java
hygieia-jenkins-plugin/src/main/java/hygieia/builder/DeployBuilder.java

Corrected directory paths for Jenkins running on windows..

---

UI/pom.xml
api/pom.xml
chat-ops-collector/docker/Dockerfile
chat-ops-collector/docker/chat-ops-properties-builder.sh
chat-ops-collector/pom.xml
core/pom.xml
docker-compose.yml
github-scm-collector/pom.xml
github-scm-collector/src/main/java/com/capitalone/dashboard/collector/DefaultGitHubClient.java
hygieia-jenkins-plugin/pom.xml
jenkins-build-collector/pom.xml
jenkins-cucumber-test-collector/pom.xml
jira-feature-collector/pom.xml
pom.xml
sonar-codequality-collector/pom.xml
stash-scm-collector/docker/Dockerfile
stash-scm-collector/docker/stash-properties-builder.sh
stash-scm-collector/pom.xml
subversion-scm-collector/docker/Dockerfile
subversion-scm-collector/docker/subversion-properties-builder.sh
subversion-scm-collector/pom.xml
test-servers/jenkins/Dockerfile
test-servers/sonar/sonar.yml
udeploy-deployment-collector/docker/Dockerfile
udeploy-deployment-collector/docker/udeploy-properties-builder.sh
udeploy-deployment-collector/pom.xml
versionone-feature-collector/docker/Dockerfile
versionone-feature-collector/docker/versionone-properties-builder.sh
versionone-feature-collector/pom.xml

Created new branch to rebase to trunk & Replace previous pull request.
#337 - Add Docker Containers for stash/svn/udeploy/versionone & cleanup docker file for jenkins test instance (5 days ago) Jim Zucker
#363 - updated the jacoco plugin to the current version (8 days ago) Jim Zucker
#364 Upgrade maven-compiler-plugin to 3.5.1 rev
#365 Jacoco not running for all subproject - Fixed jacoco/Sonar runs. There is one outstanding issue and sonar is skipped for the git and stash collectors(ref #370)
#351 - PMD Warning - Overridable method called during object construction - had to fix them in this branch as build was failing after compiler upgrade (9 days ago) Jim Zucker
It is safe to commit but I need help testing these containers: 
jira
version-one
subversion
udeploy
if somebody can give me …

Fixed the Sonar build and updated docker containers for all modules.

---

UI/src/components/widgets/codeanalysis/view.js

#368 Code collector widget showing different tech debt value - clean up unneeded code.

rebase TechDebt pull - clean up unneeded code.

---

github-scm-collector/README.md
jenkins-build-collector/README.md
jenkins-cucumber-test-collector/README.md
jira-feature-collector/README.md
sonar-codequality-collector/README.md
stash-scm-collector/README.md
subversion-scm-collector/README.md
udeploy-deployment-collector/README.md
versionone-feature-collector/README.md

the commit has only README.md files formatting.
Signed-off-by: Deepu James <mailtodeepujames@gmail.com>

format README.md for better readability

---

core/src/test/java/com/capitalone/dashboard/repository/EmbeddedMongoDBRule.java

Fix simply does a null check for the user info before using it.

Fix for issue https://github.com/capitalone/Hygieia/issues/369

---

UI/src/app/dashboard/core/data-factories/cloud-data.js
UI/src/components/widgets/cloud/config.html
UI/src/components/widgets/cloud/config.js
UI/src/components/widgets/cloud/directives/directives.js
UI/src/components/widgets/cloud/directives/metricCategory.html
UI/src/components/widgets/cloud/style.less
UI/src/components/widgets/cloud/view.html
UI/src/components/widgets/cloud/view.js
UI/test/components/feature/widgets/cloud/config.test.js
UI/test/components/feature/widgets/cloud/view.test.js

Reverts capitalone/Hygieia#531 - leakage

Revert "Further work on the UI - to bring it closer to UI designer approach"

---

UI/pom.xml

see: https://github.com/eirslett/frontend-maven-plugin/commits/master

upgrade for proxy fixes

---

api/src/main/java/com/capitalone/dashboard/service/FeatureServiceImpl.java
stash-scm-collector/pom.xml
versionone-feature-collector/src/main/java/com/capitalone/dashboard/datafactory/versionone/VersionOneDataFactoryImpl.java

Cleanup of some eclipse warnings for dead code and some incorrect maven file settings.

Eclipse cleanup

---

jira-feature-collector/src/main/java/com/capitalone/dashboard/datafactory/jira/JiraDataFactoryImpl.java
test-servers/jenkins/Dockerfile

Added better error message for 401 error, handled /n added by mac base64 to make more resiliant and updated jenkins test server docker file

Added better error message for 401 errors from JIRA

---

Setup.md

updated Mongo database name in Setup.md

---

api/src/main/java/com/capitalone/dashboard/service/CloudInstanceServiceImpl.java
api/src/main/java/com/capitalone/dashboard/service/CloudSubnetServiceImpl.java
api/src/main/java/com/capitalone/dashboard/service/CloudVolumeServiceImpl.java
api/src/main/java/com/capitalone/dashboard/service/FeatureServiceImpl.java
api/src/test/java/com/capitalone/dashboard/rest/CloudInstanceControllerTest.java
api/src/test/java/com/capitalone/dashboard/service/CloudInstanceServiceImplTest.java
api/src/test/java/com/capitalone/dashboard/service/CloudSubnetServiceImplTest.java
core/src/main/java/com/capitalone/dashboard/config/collector/CloudConfig.java
core/src/main/java/com/capitalone/dashboard/request/CloudVolumeCreateRequest.java

Cleaned up the basic ones, here is what's left
Here are the 'before errors'

#667 cleanup PMD warnings

---

.travis.yml

Please can we have travis build the gerrit integration branch?  
Signed-off-by: Markos Rendell <markosrendell@gmail.com>

Make travis build the gerrit-integration branch

---

UI/src/app/css/common.less

Pretty self-explanatory - I just added `cursor: pointer` to the logout button.

Added pointer on hover to logout button

---

subversion-scm-collector/README.md

Updated sample properties.

---

UI/gulpfile.js

Adding and removing js files will update included scripts in index.html.
resolves #741

Fixed gulp watch js files change

---

UI/src/app/dashboard/controllers/login.js
UI/src/app/dashboard/views/login.html

Fixes #702 
- General refactoring of the `LoginController` and `login.html` template.
- Fixed validation error in `LoginController`:
- Basically, this line:
```js
$scope.lg.username.$setValidity('invalidUsernamePassword', data);
```
This causes `lg.$valid` to always be false, which prevents the `loginData.login()` function from ever being called again.

Fixed password match login error

---

jenkins-build-collector/src/main/java/com/capitalone/dashboard/collector/DefaultHudsonClient.java
jenkins-build-collector/src/test/java/com/capitalone/dashboard/collector/DefaultHudsonClientTests.java
jenkins-build-collector/src/test/resources/com/capitalone/dashboard/collector/buildDetails_withRepo-emptyRemoteUrl.json
jenkins-build-collector/src/test/resources/com/capitalone/dashboard/collector/buildDetails_withRepo-noRemoteUrl.json

https://github.com/capitalone/Hygieia/issues/799

Fix for issue# 799

---

.gitignore
docker-compose.yml
jira-feature-collector/README.md

- Add basic troubleshooting guide to jira README.md

Add basic troubleshooting guide to jira README.md

---

collectors/scm/bitbucket/src/main/java/com/capitalone/dashboard/collector/DefaultBitbucketCloudClient.java
collectors/scm/bitbucket/src/main/java/com/capitalone/dashboard/collector/DefaultBitbucketServerClient.java
collectors/scm/bitbucket/src/main/java/com/capitalone/dashboard/model/GitRepo.java

- bugfix: Bitbucket scm collectors not setting branch information
- bugfix: Bitbucket scm collecotrs not setting repository url information

Bugfix for bitbucket scm collectors - set branch and repo information

---

UI/README.md
UI/src/app/dashboard/core/data-factories/collector-data.js
UI/src/components/widgets/repo/config.html
UI/src/components/widgets/repo/config.js

Fix for https://github.com/capitalone/Hygieia/issues/654

Added functionality to save credentials for private repos.

---

UI/src/app/dashboard/controllers/createDashboard.js
UI/src/app/dashboard/core/data-factories/dashboard-data.js
UI/src/app/dashboard/views/createDashboard.html
api/src/main/java/com/capitalone/dashboard/rest/DashboardController.java
api/src/main/java/com/capitalone/dashboard/service/DashboardService.java
api/src/main/java/com/capitalone/dashboard/service/DashboardServiceImpl.java
api/src/test/java/com/capitalone/dashboard/service/DashboardServiceTest.java
core/src/main/java/com/capitalone/dashboard/model/Dashboard.java

https://github.com/capitalone/Hygieia/issues/812

Fix for Issues 812 prevent creation of dashboard with same name.

---

api/src/main/java/com/capitalone/dashboard/service/CloudInstanceServiceImpl.java
api/src/main/java/com/capitalone/dashboard/service/CloudSubnetServiceImpl.java
api/src/main/java/com/capitalone/dashboard/service/FeatureServiceImpl.java
api/src/main/java/com/capitalone/dashboard/service/PipelineServiceImpl.java
api/src/main/java/com/capitalone/dashboard/service/TestResultServiceImpl.java
core/src/main/java/com/capitalone/dashboard/config/collector/CloudConfig.java
core/src/main/java/com/capitalone/dashboard/model/Dashboard.java

Fix for NPath complexity warnings
https://github.com/capitalone/Hygieia/issues/356
https://github.com/capitalone/Hygieia/issues/669
https://github.com/capitalone/Hygieia/issues/670
https://github.com/capitalone/Hygieia/issues/671

Fix for NPath complexity warnings

---

collectors/artifact/artifactory/README.md
collectors/build/bamboo/README.md
collectors/build/jenkins-cucumber/README.md
collectors/build/jenkins/README.md
collectors/build/sonar/README.md
collectors/cloud/aws/README.md
collectors/deploy/udeploy/README.md
collectors/deploy/xldeploy/README.md
collectors/feature/jira/README.md
collectors/feature/versionone/README.md
collectors/misc/chat-ops/README.md
collectors/scm/bitbucket/README.md
collectors/scm/github/README.md
collectors/scm/gitlab/README.md
collectors/scm/subversion/README.md

Fix for https://github.com/capitalone/Hygieia/issues/852

Fix for issues 852. MongoDB replicaset support readme.

---

collectors/feature/versionone/src/main/java/com/capitalone/dashboard/collector/BaseClient.java
collectors/feature/versionone/src/main/java/com/capitalone/dashboard/util/DateUtil.java

Fix sprintIndicator check for versionone.

Fix sprintIndicator check

---

README.md

I'm adding a link to the Corporate CLA to README.md

Add Corporate CLA to README.md 

---

UI/pom.xml
api/pom.xml
collectors/artifact/artifactory/pom.xml
collectors/build/bamboo/pom.xml
collectors/build/jenkins-cucumber/pom.xml
collectors/build/jenkins/pom.xml
collectors/build/sonar/pom.xml
collectors/cloud/aws/pom.xml
collectors/deploy/udeploy/pom.xml
collectors/deploy/xldeploy/pom.xml
collectors/feature/jira/pom.xml
collectors/feature/versionone/pom.xml
collectors/misc/chat-ops/pom.xml
collectors/scm/bitbucket/pom.xml
collectors/scm/github/pom.xml
collectors/scm/gitlab/pom.xml
collectors/scm/subversion/pom.xml
core/pom.xml
pom.xml

https://github.com/capitalone/Hygieia/releases/tag/Hygieia-2.0.4

Updated the pom to 2.0.5-SNAPSHOT and cut a release

---

collectors/build/sonar/docker/sonar-codequality-properties-builder.sh

Remove the default values for SONAR_USERNAME and SONAR_PASSWORD.

---

UI/src/components/widgets/pipeline/config.html
UI/src/components/widgets/pipeline/config.js
UI/src/components/widgets/pipeline/view.js
UI/src/components/widgets/product/js/commit-data.js
UI/src/components/widgets/product/product.less
UI/src/components/widgets/product/view.html
UI/src/components/widgets/product/view.js
api/src/main/java/com/capitalone/dashboard/model/PipelineResponse.java
api/src/main/java/com/capitalone/dashboard/service/PipelineServiceImpl.java
api/src/test/java/com/capitalone/dashboard/service/PipelineServiceTest.java
core/src/main/java/com/capitalone/dashboard/util/PipelineUtils.java
core/src/test/java/com/capitalone/dashboard/model/DashboardTest.java

Pr 1020 Updated - Customize stage names and dynamic display of environments for prod dashboard.
1) Changed pipeline widget modal to configure custom stage names.
2) Select production environment while configuring stage names.
3) Dynamic display of product dashboard with customized stage names for each dashboard.
4) Eliminate the duplicate entry of team dashboards in product dashboard.

Pr 1020 Updated - Customize stage names and dynamic display of environments for prod dashboard.

---

collectors/artifact/artifactory/README.md

Fix artifactory README - #1193

---

UI/src/components/widgets/deploy/config.js
UI/src/components/widgets/product/view.html
UI/src/components/widgets/product/view.js
api/src/test/java/com/capitalone/dashboard/config/TestConfig.java

1) Fix for issue 1200
2) implemented custom filter to flatten object to array and use it to display ordered stages

Fix for issue 1200 & Custom filter for ordering stages

---

collectors/feature/gitlab/docker/gitlab-properties-builder.sh

Had the wrong filename, so wasn't taking the properties.

Docker Fix for Gitlab Feature Collector

---

collectors/feature/jira/src/main/java/com/capitalone/dashboard/client/DefaultJiraClient.java

Calls to check if optional is set need to use isPresent as get will throw an exception if it is not set.
#1265

Fix for issue #1265

---

collectors/feature/gitlab/README.md
collectors/feature/gitlab/docker/gitlab-properties-builder.sh
collectors/feature/gitlab/src/main/java/com/capitalone/dashboard/collector/FeatureSettings.java
collectors/feature/gitlab/src/main/java/com/capitalone/dashboard/gitlab/GitlabUriUtility.java
collectors/feature/gitlab/src/test/java/com/capitalone/dashboard/gitlab/GitlabUriUtilityTest.java
collectors/scm/gitlab/README.md
collectors/scm/gitlab/docker/gitlab-properties-builder.sh
collectors/scm/gitlab/src/main/java/com/capitalone/dashboard/collector/GitlabSettings.java
collectors/scm/gitlab/src/main/java/com/capitalone/dashboard/gitlab/GitlabUrlUtility.java
collectors/scm/gitlab/src/test/java/com/capitalone/dashboard/collector/GitlabUrlUtilityTest.java

Resolves #1291 Added an optional path parameter in case it is needed to access the instance of gitlab.

Gitlab optional path

---

UI/src/components/widgets/codeanalysis/view.html
UI/src/components/widgets/codeanalysis/view.js
collectors/build/sonar/README.md
collectors/build/sonar/src/main/java/com/capitalone/dashboard/collector/DefaultSonar6Client.java
collectors/build/sonar/src/main/java/com/capitalone/dashboard/collector/DefaultSonarClient.java
collectors/build/sonar/src/main/java/com/capitalone/dashboard/collector/SonarClient.java
collectors/build/sonar/src/main/java/com/capitalone/dashboard/collector/SonarClientSelector.java
collectors/build/sonar/src/main/java/com/capitalone/dashboard/collector/SonarCollectorTask.java
collectors/build/sonar/src/main/java/com/capitalone/dashboard/collector/SonarSettings.java
collectors/build/sonar/src/main/java/com/capitalone/dashboard/model/SonarCollector.java
collectors/build/sonar/src/test/java/com/capitalone/dashboard/collector/DefaultSonar6ClientTest.java
collectors/build/sonar/src/test/java/com/capitalone/dashboard/collector/SonarClientSelectorTest.java
collectors/build/sonar/src/test/java/com/capitalone/dashboard/collector/SonarCollectorTaskTest.java
collectors/build/sonar/src/test/resources/com/capitalone/dashboard/collector/sonar6analyses.json
collectors/build/sonar/src/test/resources/com/capitalone/dashboard/collector/sonar6measures.json
collectors/build/sonar/src/test/resources/com/capitalone/dashboard/collector/sonar6projects.json

Fix for https://github.com/capitalone/Hygieia/issues/1311.
Changes: 
1. Took changes suggested from the discussion thread. 
2. Added tests
3. UI changes - since sonar 5, rules compliance was deprecated. Instead a "quality gate" was introduced. Made UI change to display quality gate when available 
Screen shot:

Support for Sonar 6+ and UI changes

---

.travis.yml
hygieia-jenkins-plugin/src/main/java/hygieia/builder/ArtifactBuilder.java
hygieia-jenkins-plugin/src/main/java/hygieia/builder/BuildBuilder.java
pom.xml

add in jenkins plugin to main project. Inline getChangeSets as it's not allowed by the annotation.

minimum changes to allow project to build

---

UI/src/components/widgets/codeanalysis/config.html
UI/src/components/widgets/codeanalysis/view.js

Each tool has its own way of categorizing issues such as "Critical", "Blocker" etc and then some tool has "High", "Medium", "Low" etc. This change will display whatever metric is collected by simply using the name, value pair.

Changes to allow other security analysis tool to show stats.

---

UI/src/app/dashboard/core/data-factories/performance-data.js
UI/src/components/widgets/codeanalysis/view.js

AppDynamics and Quality widget issues
Fix for https://github.com/capitalone/Hygieia/issues/1422

AppDynamics and Quality widget issues

---

api/docker/properties-builder.sh
collectors/artifact/artifactory/docker/artifactory-properties-builder.sh
collectors/build/bamboo/docker/bamboo-build-properties-builder.sh
collectors/build/jenkins-cucumber/docker/jenkins-cucumber-test-properties-builder.sh
collectors/build/jenkins/docker/jenkins-build-properties-builder.sh
collectors/build/sonar/docker/sonar-codequality-properties-builder.sh
collectors/deploy/udeploy/docker/udeploy-properties-builder.sh
collectors/deploy/xldeploy/docker/xldeploy-properties-builder.sh
collectors/feature/gitlab/docker/gitlab-properties-builder.sh
collectors/feature/jira/docker/jira-properties-builder.sh
collectors/feature/versionone/docker/versionone-properties-builder.sh
collectors/library-policy/nexus-iq-collector/docker/nexus-iq-properties-builder.sh
collectors/misc/chat-ops/docker/chat-ops-properties-builder.sh
collectors/scm/bitbucket/docker/bitbucket-properties-builder.sh
collectors/scm/github/docker/github-properties-builder.sh
collectors/scm/gitlab/docker/gitlab-properties-builder.sh
collectors/scm/subversion/docker/subversion-properties-builder.sh

Had to change from "return" to "exit 0" because return isn't supported how this needs to be used.  Has the same effect, but it actually works properly now.

Property builder fix

---

api/docker/Dockerfile

pull #873  broke docker:build of api  - this change only fixes that one fault

docker:build - bug in api Dockerfile

---

getting_started.html

@satishc1  - Moved section to test changes on capitalone.io

Moved 'Build Hygieia' section

---

README.md

Made a few minor suggestions and added content about Hygieia's features from [https://developer.capitalone.com/opensource-projects/hygieia/](url).

Suggest minor changes to README.md

---

getting_started.html

@satishc1 - Corrected hyperlinks to Jenkins collector and plugin.

Jenkins Collector - Link Correction

---

pages/hygieia/getting_started.md

@satishc1 : Modified getting_started.html

Deleting redirection to DevExchange

---

_data/sidebars/hygieia_sidebar.yml
_data/topnav.yml
pages/hygieia/contact.md
pages/product1/p1_landing_page.html

@satishc1 - Fixed links to Introduction page and images; added contact.md

Fixed links, added contact.md

---

UI/src/app/dashboard/controllers/admin.js
UI/src/app/dashboard/controllers/editApiToken.js
UI/src/app/dashboard/core/data-factories/user-data.js
UI/src/app/dashboard/directives/date-picker.js
UI/src/app/dashboard/views/admin.html
UI/src/app/dashboard/views/datePicker.html
UI/src/app/dashboard/views/editApiToken.html
api-audit/src/main/java/com/capitalone/dashboard/service/ApiTokenService.java
api-audit/src/main/java/com/capitalone/dashboard/service/ApiTokenServiceImpl.java
api/src/main/java/com/capitalone/dashboard/rest/AdminController.java
api/src/main/java/com/capitalone/dashboard/service/ApiTokenService.java
api/src/main/java/com/capitalone/dashboard/service/ApiTokenServiceImpl.java

1) Added the functionality to delete tokens
2) Added the functionality to update the expiration time
3) Moved date picker code to directive for reuse
**Edit and delete options added**
**Edit View**

Added ability to edit API token exp date and remove tokens

---

UI/src/app/dashboard/views/createDashboard.html
UI/src/app/dashboard/views/editDashboard.html
api/src/main/java/com/capitalone/dashboard/service/CmdbServiceImpl.java
core/src/main/java/com/capitalone/dashboard/repository/CmdbRepository.java

1) Can now search by the Common Name in addition to the CI name.

Updating Create and Edit Dashboard UI 

---

collectors/build/jenkins-codequality/src/main/java/com/capitalone/dashboard/collector/HttpJenkinsClient.java
collectors/build/jenkins-codequality/src/main/java/com/capitalone/dashboard/jenkins/JobContainer.java
collectors/build/jenkins-codequality/src/test/java/com/capitalone/dashboard/collector/HttpJenkinsClientTest.java
collectors/build/jenkins-codequality/src/test/java/com/capitalone/dashboard/collector/ResponseConversionTest.java

fixes JobContainer conversion from json with performing get on jenkins job request

correct issue with job container not having default constructor

---

collectors/artifact/artifactory/src/main/java/com/capitalone/dashboard/collector/DefaultArtifactoryClient.java

The rest POST should be using text/plain not application/json.

Fix artifactory content type for rest POSTs

---

collectors/scm/github/src/main/java/com/capitalone/dashboard/collector/DefaultGitHubClient.java

Use the "statuses_url" provided by the pull request API response.
"statuses_url" points to /repos/:owner/:repo/statuses/:ref which
returns all commit statuses for a given ref.
/repos/:owner/:repo/commits/:ref/status is more convenient it
returns the most recent status for each context. This is ok. We can
calculate the most recent status from /repos/:owner/:repo/statuses/:ref.
Using /repos/:owner/:repo/statuses/:ref also contains the "creator"
property for the commit status. This information isn't used at the
moment but will become useful when GitHub Apps adoption is
more widespread.

Bug fix for GitHub fetch commit statuses.

---

collectors/scm/github/src/main/java/com/capitalone/dashboard/collector/GitHubCollectorTask.java

Fix commit type for squash merged and rebase merged PRs. They currently show up as New commits instead of Merge. This will not fix old commits that exist in the database already. Those will still show up as type new unless you do a data cleanup.

Fix commit type for squash merged and rebase merged PRs

---

pages/hygieia/collectors/cmdb/hpsm.md

@satishc1 
- Added additional properties in the section, 'Sample Application Properties File'.

Additional HPSM Properties

---

pages/hygieia/api/api.md
pages/hygieia/collectors/artifact/artifactory.md
pages/hygieia/collectors/build/bamboo.md
pages/hygieia/collectors/build/jenkins-codequality.md
pages/hygieia/collectors/build/jenkins-cucumber.md
pages/hygieia/collectors/build/jenkins.md
pages/hygieia/collectors/build/sonar.md
pages/hygieia/collectors/cloud/aws.md
pages/hygieia/collectors/cmdb/hpsm.md
pages/hygieia/collectors/deploy/udeploy.md
pages/hygieia/collectors/deploy/xldeploy.md
pages/hygieia/collectors/feature/feature-gitlab.md
pages/hygieia/collectors/feature/jira.md
pages/hygieia/collectors/feature/versionone.md
pages/hygieia/collectors/library-policy/nexus-iq-collector.md
pages/hygieia/collectors/misc/chat-ops.md
pages/hygieia/collectors/performance/appdynamics.md
pages/product1/select_dashboard.md

@satishc1 
- Updated Troubleshooting Instructions
- Team review comments

Updated Comments and Troubleshooting Instructions in API

---

pages/product1/pipeline_view.md
pages/product1/product_view.md
pages/product1/select_dashboard.md

@satishc1 
- Modified image links

Image Links

---

_data/sidebars/hygieia_sidebar.yml
pages/hygieia/api-audit/api-audit.md
pages/hygieia/api/api.md
pages/hygieia/troubleshoot.md
pages/product1/signup.md

@satishc1 
- Created FAQ document
- Added SSO-related information
- Add FAQ to sidebar
- Changed link for encrypted properties to point to setup.md

FAQ and SSO documents

---

collectors/feature/jira/src/main/java/com/capitalone/dashboard/client/story/StoryDataClientImpl.java

Hi Satish,
Have added the logic to handle and log invalid (non-number) values for Story Point Field Values.
And yes, I think handling the NumberFormatException is better way of doing it, that way it lets us log an error message as well. Thanks !

Story Points Field Value: Logic to handle invalid (non-number) values

---

README.md

Changing from www.capitalone.io to capitalone.github.io

Updating the root URL for the pages

---

pages/hygieia/collectors/feature/jira.md

@satishc1 @subodhbattina 
- Added JIRA troubleshooting Instructions

Troubleshooting Instructions -JIRA

---

UI/src/components/widgets/codeanalysis/view.js

Before the change this is what the link looked like. After the change you can see that you reach the appropriate scan results. 
This solves [#1851](https://github.com/capitalone/Hygieia/issues/1851)

Updated the link to the sonar scan

---

core/pom.xml
core/src/main/java/com/capitalone/dashboard/model/ChangeOrder.java
core/src/main/java/com/capitalone/dashboard/model/Cmdb.java
core/src/main/java/com/capitalone/dashboard/model/Incident.java

Updated timestamps in models used by hpsm collector (Cmdb, ChangeOrder, Incident) to use Long for storage.  Re-added and corrected String set methods for timestamps

Updated timestamps in models used by hpsm collector.

---

pages/hygieia/api-audit/api-audit.md
pages/hygieia/api/api.md
pages/hygieia/architecture.md
pages/hygieia/collectors/scm/bitbucket.md
pages/hygieia/collectors/scm/github.md
pages/hygieia/collectors/scm/gitlab.md
pages/product1/Introduction.md

@satishc1 
- Fixed links to "Encryption of Private Repos"
- Added note on audit API in architecture.md
- Editorial changes

Link Fixes

---

api/src/main/java/com/capitalone/dashboard/service/CollectorServiceImpl.java
api/src/test/java/com/capitalone/dashboard/service/CollectorServiceTest.java
core/src/main/java/com/capitalone/dashboard/repository/CustomRepositoryQuery.java
core/src/main/java/com/capitalone/dashboard/repository/CustomRepositoryQueryImpl.java

Build widget fix - Search with job name

Build widget fix - Search with job name

---

api/src/main/java/com/capitalone/dashboard/service/CollectorServiceImpl.java
api/src/test/java/com/capitalone/dashboard/service/CollectorServiceTest.java
core/src/main/java/com/capitalone/dashboard/repository/CustomRepositoryQuery.java
core/src/main/java/com/capitalone/dashboard/repository/CustomRepositoryQueryImpl.java

Reverts capitalone/Hygieia#2017

Revert "Build widget fix - Search with job name"

---

pages/hygieia/collectors/build/jenkins.md
pages/product1/widget_view.md

- Modified Standard Widgets Definition in widget_view.md
- Modified Jenkins Build Properties File in jenkins.md

Modified Widgets and Jenkins Build Collector Readmes

---

collectors/build/sonar/src/main/java/com/capitalone/dashboard/collector/DefaultSonar6Client.java

This commit fix the issue #2028

Fix sonar CodeQuallity collector parse error (#2028)

---

UI/src/app/dashboard/services/dashboardValidationService.js

https://github.com/capitalone/Hygieia/issues/1599#issuecomment-326066852

[Fix] TypeError: Cannot read property 'name' of undefined

---

UI/src/app/dashboard/core/data-factories/collector-data.js
UI/src/components/widgets/repo/config.html

Hide label for code repo 

---

pages/product1/widget_view.md

Added "Personal Access Token" for Code Repo widget in widgets.md

Git Private Repo Documentation

---

api/src/main/java/com/capitalone/dashboard/service/BuildServiceImpl.java

Modified Hudson collector - push based call

Modified Hudson collector - push based call

---

collectors/scm/github-graphql/src/main/java/com/capitalone/dashboard/collector/DefaultGitHubClient.java

Accept personalAccessToken at repo level

Accept personalAccessToken at repo level

---

api-audit/src/main/java/com/capitalone/dashboard/evaluator/PerformanceTestResultEvaluator.java

Testcase steps array have data in the following order Target, achieved. Currently the code is always updating Achieved property with "0" and target property with the achieved value. This fix should set target property with target value and achieved property with achieved value.

Fix for Target and Achieved

---

api/docker/properties-builder.sh
collectors/scm/bitbucket/docker/properties-builder.sh

Some properties are missing from two properties-builder scripts. Discussion at https://github.com/capitalone/Hygieia/issues/2154

Missing properties in properties-builder scripts See #2154

---

api-audit/src/test/java/com/capitalone/dashboard/common/CodeReviewEvaluatorLegecyTest.java
api-audit/src/test/java/com/capitalone/dashboard/common/CodeReviewEvaluatorTest.java
api-audit/src/test/java/com/capitalone/dashboard/common/CommonCodeReviewTest.java
collectors/scm/github-graphql/src/main/java/com/capitalone/dashboard/collector/DefaultGitHubClient.java

Audit api - Test cases for system id check

Audit api - Test cases for system id check 

---

pages/hygieia/api-audit/api-audit.md

featureIDPattern=((?<!([A-Za-z]{1,10})-?)[A-Z]+-\\d+)

New property featureIDPattern for api-audit.properties

---

UI/src/app/dashboard/controllers/createDashboard.js

fixes https://github.com/capitalone/Hygieia/issues/2090

fixes ConfigurationItem null when creating a new dashboard

---

core/src/main/java/com/capitalone/dashboard/model/Cmdb.java

Adding Environments field to cmdb model

---

pages/hygieia/collectors/build/sonar.md

@Sbrenthughes Added Sonar login credentials to application.properties

Modified application.properties for Sonar collector

---

UI/pom.xml

* Fixes https://github.com/capitalone/Hygieia/issues/2246

Fix for #2246, changing npm url from http to https

---

pages/hygieia/database.html
pages/hygieia/setup.md

@nireeshT Added prerequisites section with recommended versions in setup.md.

Added Maven version to setup.md

---

pages/hygieia/troubleshoot.md

@nireeshT added FAQ about the properties "github.key" and "github.personalAccessToken"

Updated FAQ Document

---

pages/product1/signup.md

@nireeshT Added General Configurations tab to Admin settings.

Property Management Documentation

---

_data/sidebars/hygieia_sidebar.yml
pages/hygieia/dbschema.md

@nireeshT @Sbrenthughes Document with the list of DB Collections.

Database Schema

---

api-audit/src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluator.java
api-audit/src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluatorLegacy.java
api-audit/src/test/java/com/capitalone/dashboard/common/CodeReviewEvaluatorLegecyTest.java
api-audit/src/test/java/com/capitalone/dashboard/common/CodeReviewEvaluatorTest.java

Peer review audit - Direct commits to base

Peer review audit - Direct commits to base

---

pages/hygieia/audit_apis.md

@nireeshT added SCA sample request.

SCA Sample Request

---

api/src/main/java/com/capitalone/dashboard/service/PerformanceServiceImpl.java
core/src/main/java/com/capitalone/dashboard/model/Performance.java
core/src/main/java/com/capitalone/dashboard/request/PerformanceCreateRequest.java

1) Fixes performance/create api not having the ability to pass in metrics.
2) Fixes CollectorType 
3) Fixes Null Pointer when hygieiaId isn't passed in

Fix for performance api to pass in metrics

---

api-audit/src/main/java/com/capitalone/dashboard/evaluator/CodeQualityEvaluator.java
api-audit/src/main/java/com/capitalone/dashboard/rest/DashboardAuditController.java
api-audit/src/main/java/com/capitalone/dashboard/service/DashboardAuditService.java
api-audit/src/main/java/com/capitalone/dashboard/service/DashboardAuditServiceImpl.java
collectors/build/sonar/src/main/java/com/capitalone/dashboard/model/SonarCollector.java
core/src/main/java/com/capitalone/dashboard/repository/CollectorItemRepository.java

Audit api quality gate metrics fix for 6.7 
enable api to get sonar project id

Api audit - SCA metrics fix for 6.7

---

api-audit/src/main/java/com/capitalone/dashboard/evaluator/StaticSecurityAnalysisEvaluator.java
api/src/test/java/com/capitalone/dashboard/rest/CodeQualityControllerTest.java
collectors/build/jenkins-codequality/src/main/java/com/capitalone/dashboard/utils/CodeQualityMetricsConverter.java
collectors/build/jenkins-codequality/src/test/java/com/capitalone/dashboard/utils/CodeQualityMetricsConverterTest.java
collectors/build/sonar/src/main/java/com/capitalone/dashboard/collector/DefaultSonar6Client.java
collectors/build/sonar/src/main/java/com/capitalone/dashboard/collector/DefaultSonarClient.java
collectors/misc/score/src/main/java/com/capitalone/dashboard/widget/QualityWidgetScore.java
collectors/misc/score/src/test/java/com/capitalone/dashboard/widget/QualityWidgetScoreTest.java
core/src/main/java/com/capitalone/dashboard/model/CodeQualityMetric.java
hygieia-jenkins-plugin/src/main/java/hygieia/builder/SonarBuilder.java
hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/utils/CodeQualityMetricsConverter.java
hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/utils/CodeQualityMetricsConverterTest.java

Changed the datatype of 'CodeQualityMetric' 'value' variable to String.
And associated dependent changes

Changed the datatype of 'CodeQualityMetric' 'value' variable to String

---

collectors/cloud/aws/pom.xml
collectors/cloud/aws/src/main/java/com/capitalone/dashboard/collector/AWSCloudCollectorTask.java

- Removed unused dependencies
- Fixed a typo

Remove unused dependencies from AWS Cloud Collector Microservice

---

api-audit/src/main/java/com/capitalone/dashboard/common/CommonCodeReview.java
api-audit/src/test/java/com/capitalone/dashboard/common/CommonCodeReviewTest.java

Fixed the Audit Status for 'error' to PEER_REVIEW_LGTM_ERROR from PEER_REVIEW_LGTM_PENDING

Fixed the Audit Status for 'error' to PEER_REVIEW_LGTM_ERROR

---

collectors/build/sonar/src/main/java/com/capitalone/dashboard/collector/DefaultSonar6Client.java
collectors/build/sonar/src/test/java/com/capitalone/dashboard/collector/DefaultSonar6ClientTest.java
collectors/build/sonar/src/test/resources/com/capitalone/dashboard/collector/sonar6analysesNull.json

Sonar collector - null check for project data

Sonar collector - null check for project data

---

.travis.yml

Hopefully fixes the Permission denied error in travis builds.

recursively chown home

---

api-audit/src/main/java/com/capitalone/dashboard/common/CommonCodeReview.java
api-audit/src/test/java/com/capitalone/dashboard/common/CommonCodeReviewTest.java

Reverting changes from PR #2431, to avoid downstream impacts at this point.

Revert "Merge pull request #2431 from battinasubodh/master": 

---

hygieia-jenkins-plugin/pom.xml

incremented the version for hygiene Jenkins plugin

Version increment for hygieia jenkins plugin

---

pages/hygieia/audit_apis.md

widget display on UI is basing on last updated timestamp

widget display on UI is basing on last updated

---

pages/hygieia/collectors/cloud/aws-cloudwatch-collector.md

documentation to go with cloud watch collector

---

UI/src/components/widgets/codeanalysis/config.html
UI/src/components/widgets/codeanalysis/config.js
collectors/build/sonar/src/main/java/com/capitalone/dashboard/collector/SonarCollectorTask.java
collectors/build/sonar/src/main/java/com/capitalone/dashboard/collector/SonarSettings.java
collectors/build/sonar/src/main/java/com/capitalone/dashboard/model/SonarCollector.java
collectors/build/sonar/src/test/java/com/capitalone/dashboard/collector/SonarCollectorTaskTest.java

This PR changes include 
addition - "nicename" attribute to static code quality collector_items.

Nicename - Sonar collector

---

UI/src/app/dashboard/views/createDashboard.html
UI/src/app/dashboard/views/editDashboard.html
api/src/main/java/com/capitalone/dashboard/service/DashboardServiceImpl.java

1) Fixes issue when trying to save new Business Application to a dashboard
2) Cleanup logic for save in API
3) Adds search by common name field in the Create/Edit Dashboard screens

Enhancement to search by commonNam in create/edit Dashboard

---

pages/hygieia/collectors/misc/score.md

Fixes properties to remove confusion when setting up score collector

Fixed for properties wording

---

pages/hygieia/collectors/artifact/artifactory.md

Updated artifactory collector properties

Updated artifactory collector properties

---

UI-tests/pom.xml
UI/pom.xml
api-audit/pom.xml
api/pom.xml
collectors/artifact/artifactory/pom.xml
collectors/build/bamboo/pom.xml
collectors/build/jenkins-codequality/pom.xml
collectors/build/jenkins-cucumber/pom.xml
collectors/build/jenkins/pom.xml
collectors/build/sonar/pom.xml
collectors/cloud/aws/pom.xml
collectors/cmdb/hpsm/pom.xml
collectors/deploy/udeploy/pom.xml
collectors/deploy/xldeploy/pom.xml
collectors/feature/gitlab/pom.xml
collectors/feature/jira/pom.xml
collectors/feature/rally/pom.xml
collectors/feature/versionone/pom.xml
collectors/library-policy/nexus-iq-collector/pom.xml
collectors/misc/chat-ops/pom.xml
collectors/misc/score/pom.xml
collectors/performance/appdynamics/pom.xml
collectors/scm/bitbucket/pom.xml
collectors/scm/github-graphql/pom.xml
collectors/scm/github/pom.xml
collectors/scm/gitlab/pom.xml
collectors/scm/subversion/pom.xml
core/pom.xml
hygieia-jenkins-plugin/pom.xml
pom.xml

- updates version number to 3.0.0 to prep for release.
- after this is merged a tagged release for 3.0.0 will be created

Updated version number

---

UI/src/components/widgets/codeanalysis/config.html
UI/src/components/widgets/codeanalysis/config.js
UI/src/components/widgets/codeanalysis/testdetails.html
UI/src/components/widgets/codeanalysis/view.html

- Fixes Issue with wrong data being defaulted when viewing the configuration popup of the Widget
- Fixes issue with Test Data not being displayed in popup when clicked
- Fixes issue with latency while trying to configure the Quality Widget
- Fixes issue with incorrect data being stored in the Quality Widget
- Added Search filtering for Test input boxes. Tests inputs no longer display all records, only the top 20 that match the search string
- truncates Test name in the display section with too long and adds tooltip to see full name

Fixes Several Quality Widget Issues

---

pages/hygieia/Build/builddocker.md

@subodhbattina  Deleted "Create Dashboard User" section in Step 3.

Changes to Step 3

---

api/src/main/java/com/capitalone/dashboard/ApiSettings.java
api/src/main/java/com/capitalone/dashboard/service/BuildServiceImpl.java
api/src/test/java/com/capitalone/dashboard/service/BuildServiceTest.java

Added a feature toggle via ApiSettings to lookup dashboards for BuildData create request(compatible from v3 onwards)

Added feature toggle to lookup dashboards

---

api/src/main/java/com/capitalone/dashboard/webhook/github/GitHubCommitV3.java
api/src/main/java/com/capitalone/dashboard/webhook/github/GitHubPullRequestV3.java

Minor update: Added, decryption for the repo token

Minor update: Added, decryption for the repo token

---

api/src/main/java/com/capitalone/dashboard/webhook/github/GitHubCommitV3.java
api/src/main/java/com/capitalone/dashboard/webhook/github/GitHubPullRequestV3.java

Moved the token decrypt to only decrypt for private repos

Moved the token decrypt to only decrypt for private repos

---

api/src/main/java/com/capitalone/dashboard/webhook/github/GitHubCommitV3.java
api/src/main/java/com/capitalone/dashboard/webhook/github/GitHubPullRequestV3.java

Added local cache to GitCommitV3 for LDAPLDN, and enhanced Logs

Added local cache to GitCommitV3 for LDAPLDN, and enhanced Logs

---

api/src/main/java/com/capitalone/dashboard/webhook/github/GitHubCommitV3.java
api/src/test/java/com/capitalone/dashboard/webhook/github/GitHubCommitV3Test.java

Added new attributes for files changed(Added, removed and modified) for a commit

Included change to capture file names

---

api-audit/src/main/java/com/capitalone/dashboard/evaluator/PerformanceTestResultEvaluator.java

This PR is created to address the duplicate results of PERF_TYPE audit api response

Audit API PERF_TEST fix for duplicate results 

---

UI/src/app/dashboard/controllers/addServiceAccount.js
UI/src/app/dashboard/controllers/admin.js
UI/src/app/dashboard/controllers/editServiceAccount.js
UI/src/app/dashboard/core/data-factories/service-account-data.js
UI/src/app/dashboard/views/add-service-account.html
UI/src/app/dashboard/views/admin.html
UI/src/app/dashboard/views/edit-service-account.html
api-audit/pom.xml
api-audit/src/main/java/com/capitalone/dashboard/common/CommonCodeReview.java
api-audit/src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluator.java
api-audit/src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluatorLegacy.java
api-audit/src/test/java/com/capitalone/dashboard/common/CodeReviewEvaluatorLegecyTest.java
api-audit/src/test/java/com/capitalone/dashboard/common/CodeReviewEvaluatorTest.java
api-audit/src/test/java/com/capitalone/dashboard/common/CommonCodeReviewTest.java
api/pom.xml
api/src/main/java/com/capitalone/dashboard/request/ServiceAccountRequest.java
api/src/main/java/com/capitalone/dashboard/rest/ServiceAccountController.java
api/src/main/java/com/capitalone/dashboard/service/ServiceAccountService.java
api/src/main/java/com/capitalone/dashboard/service/ServiceAccountServiceImpl.java
api/src/main/java/com/capitalone/dashboard/webhook/github/GitHubCommitV3.java
api/src/test/java/com/capitalone/dashboard/config/TestAuthConfig.java
api/src/test/java/com/capitalone/dashboard/config/TestConfig.java
api/src/test/java/com/capitalone/dashboard/config/TestDefaultAuthConfig.java
api/src/test/java/com/capitalone/dashboard/webhook/github/GitHubCommitV3Test.java

This PR includes 
SystemId whitelisting with allowed users

SystemId whitelisting with allowed users 

---

api-audit/src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluator.java
api-audit/src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluatorLegacy.java
api-audit/src/test/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluatorTest.java

Audit review - SystemId changes for allowed users

Audit review - SystemId changes for allowed users

---

api/src/main/java/com/capitalone/dashboard/webhook/github/GitHubCommitV3.java
api/src/main/java/com/capitalone/dashboard/webhook/github/GitHubIssueV3.java
api/src/main/java/com/capitalone/dashboard/webhook/github/GitHubPullRequestV3.java

A minor update to enable the collector item, if it already exists.

A minor update to enable the collector item, if it already exists.

---

api-audit/src/main/java/com/capitalone/dashboard/common/CommonCodeReview.java
api-audit/src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluator.java
api-audit/src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluatorLegacy.java
api-audit/src/test/java/com/capitalone/dashboard/common/CommonCodeReviewTest.java

Audit status for SystemId allowed users.
SCM_AUTHOR_WHITELISTED_USER

Audit status for SystemId allowed users

---

UI/src/components/widgets/codeanalysis/view.js

- This change can able  to calculate Success percentage for both "Manual" and "Functional" tests in Code analysis test widget.
-

Ui change to count the percentage for Manual Tests 

---

api/src/main/java/com/capitalone/dashboard/webhook/github/GitHubCommitV3.java
api/src/main/java/com/capitalone/dashboard/webhook/github/GitHubPullRequestV3.java
api/src/test/java/com/capitalone/dashboard/webhook/github/GitHubCommitV3Test.java
api/src/test/java/com/capitalone/dashboard/webhook/github/GitHubPullRequestV3Test.java

Updates to handle multiple commits with the same rev num, url, and branch in case they do exist in the database

Updates to handle multiple commits with the same rev num, url, and branch

---

hygieia-jenkins-plugin/src/main/java/hygieia/builder/DeployBuilder.java

this is a error

---

api-audit/src/main/resources/static/swagger/index.html
api/src/main/resources/static/swagger/index.html
api/src/test/java/com/capitalone/dashboard/logging/KeyValueLoggingFilterTest.java
collectors/feature/jira/src/main/java/com/capitalone/dashboard/util/ClientUtil.java
hygieia-jenkins-plugin/src/main/java/hygieia/utils/WildCardURL.java

Primarily an accessibility concern for screen reader software.

Added HTML lang="en"

---

pom.xml

Revert "Error Prone Static Analysis Tool"

---

pages/hygieia/UI/ui.md

Remove Bower documentation

---

collectors/audit/nfrr/src/main/java/com/capitalone/dashboard/collector/AuditCollectorUtil.java
collectors/audit/nfrr/src/main/java/com/capitalone/dashboard/model/Audit.java
collectors/audit/nfrr/src/test/java/com/capitalone/dashboard/collector/AuditCollectorTaskTest.java

This PR is created to collect traceability details in audit results collection from audit response.

Collect traceability details from audit response

---

collectors/audit/nfrr/src/main/java/com/capitalone/dashboard/collector/AuditCollectorUtil.java

NFRR Audit results updated with Library policy url and SSA result status updates

NFRR enhancements in library policy and SSA audit results

---

UI/src/app/dashboard/directives/hideEmpty.js

cant run .every on undefined- check if defined before calling

check for undefined before running function

---

UI/src/components/widgets/product/js/commit-data.js

Added code to restrict additional timestamps (durations) within stageDurations, that impacted average time within product-dashboard

---

api/src/main/java/com/capitalone/dashboard/service/DashboardRemoteServiceImpl.java
api/src/test/java/com/capitalone/dashboard/service/DashboardRemoteServiceTest.java
api/src/test/resources/dashboardRemoteRequests/Remote-Request-Create-Invalid-Valid-Users.json

Validated user list was not being passed into the create function

Fix issue with remote create

---

collectors/artifact/artifactory/pom.xml
collectors/artifact/artifactory/src/main/java/com/capitalone/dashboard/collector/ArtifactoryCollectorTask.java
collectors/artifact/artifactory/src/main/java/com/capitalone/dashboard/collector/DefaultArtifactoryClient.java
collectors/artifact/artifactory/src/test/java/com/capitalone/dashboard/collector/DefaultArtifactoryClientTest.java

Artifactory collector changes
1) Save binary artifact ; ARTIFACT_BASED 
2) Changed timestamp from string to long (millis)

Artifactory collector changes

---

pages/hygieia/collectors/feature/jira.md

Updating Docs to add the following properties.

Updating Documentation For Jira Collector

---

collectors/artifact/artifactory/pom.xml

Artifactory collector - core version upgrade

Artifactory collector - core version upgrade 

---

api-audit/src/main/java/com/capitalone/dashboard/evaluator/StaticSecurityAnalysisEvaluator.java
api-audit/src/main/java/com/capitalone/dashboard/response/AuditReviewResponse.java
api-audit/src/test/java/com/capitalone/dashboard/evaluator/StaticSecurityAnalysisEvaluatorTest.java
api-audit/src/test/java/com/capitalone/dashboard/service/DashboardAuditServiceTest.java
api-audit/src/test/resources/expected/CodeQuality.json
api-audit/src/test/resources/expected/LibraryPolicyAudit.json
api-audit/src/test/resources/expected/LibraryPolicyAuditWithDisposition-fail.json
api-audit/src/test/resources/expected/LibraryPolicyAuditWithDisposition-ok.json
api-audit/src/test/resources/expected/Performance.json
api-audit/src/test/resources/expected/StaticSecurityAnalysisAudit.json
api/src/test/java/com/capitalone/dashboard/webhook/github/GitHubCommitV3Test.java

This PR is created to support security scan audit api response with collector item options for audit entity identification.

AppSec audit api updated with collector item options

---

collectors/audit/nfrr/pom.xml

This PR is created just to update nfrr's core version.

nfrr core version updated

---

api-audit/src/main/java/com/capitalone/dashboard/evaluator/StaticSecurityAnalysisEvaluator.java
api-audit/src/test/java/com/capitalone/dashboard/evaluator/StaticSecurityAnalysisEvaluatorTest.java

Remove 100 special case for audit api

---

UI/src/components/widgets/build/detail.html
UI/src/components/widgets/codeanalysis/librarypolicydetails.html
UI/src/components/widgets/codeanalysis/testdetails.html
UI/src/components/widgets/codeanalysis/view.html
UI/src/components/widgets/deploy/detail.html
UI/src/components/widgets/feature/view.html
UI/src/components/widgets/rally/rallyBuildDetail.html
api-audit/src/main/resources/static/swagger/swagger-ui.js
api-audit/src/main/resources/static/swagger/swagger-ui.min.js
api/src/main/resources/static/swagger/swagger-ui.js
api/src/main/resources/static/swagger/swagger-ui.min.js

Currently we have some issues that were being flagged on eratocode that involve target="_blank".  Here's a summary of the issue: https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

Fix security issues with target=_blank

---

api-audit/src/main/java/com/capitalone/dashboard/evaluator/RegressionTestResultEvaluator.java
api-audit/src/test/java/com/capitalone/dashboard/evaluator/RegressionTestResultEvaluatorTest.java

Counting Test cases instead of Test suite counts.

Audit API fix for Regression Tests

---

pages/hygieia/collectors/library-policy/nexus-iq-collector.md

The code expects a List<String>  for usernames and passwords.

Updating Documentation to Reflect Proper usage

---

api/pom.xml

api module's hygieia-core version updated

api core version update

---

README.md

Changed it's to its in the opening paragraph to reflect proper usage.

Update README.md file to correct small grammar error

---

api-audit/src/main/java/com/capitalone/dashboard/ApiSettings.java
api-audit/src/main/java/com/capitalone/dashboard/evaluator/LibraryPolicyEvaluator.java

OSS enhancement- Api Audit changes
1) Included validations on threat duration in "Open" status

OSS enhancement- Api Audit 

---

collectors/build/jenkins/pom.xml
collectors/build/jenkins/src/main/java/com/capitalone/dashboard/collector/HudsonSettings.java
collectors/build/jenkins/src/main/java/com/capitalone/dashboard/collector/RestOperationsSupplier.java

Gives the user the ability to set the timeout values for the RestTemplate

closes #2574 Jenkins collector timing out on larger calls

---

api-audit/src/main/java/com/capitalone/dashboard/ApiSettings.java
api-audit/src/main/java/com/capitalone/dashboard/evaluator/LibraryPolicyEvaluator.java

Added max age

---

api-audit/src/main/java/com/capitalone/dashboard/ApiSettings.java
api-audit/src/main/java/com/capitalone/dashboard/evaluator/LibraryPolicyEvaluator.java

This PR includes : 
1) Settings for Critical/High - Security/License vulnerabilites max age

Critical/High - Security/License vulnerabilites age

---

collectors/cloud/aws/src/main/java/com/capitalone/dashboard/collector/DefaultAWSCloudClient.java

Fixes null pointer when proxy info is commented out in properties.

Aws collector null pointer

---

api-audit/src/main/java/com/capitalone/dashboard/evaluator/RegressionTestResultEvaluator.java

This PR is created to add test case counts in critical test audit api response.

Test Case Counts in Critical Test Audit API Response

---

collectors/scm/github-graphql/src/main/java/com/capitalone/dashboard/collector/GitHubCollectorTask.java
collectors/scm/github-graphql/src/main/java/com/capitalone/dashboard/collector/GitHubSettings.java

Add flag for github ratelimit

---

collectors/scm/github-graphql/src/main/java/com/capitalone/dashboard/collector/DefaultGitHubClient.java
collectors/scm/github-graphql/src/main/java/com/capitalone/dashboard/model/GitHubGraphQLQuery.java

Modified graphql query to include 
1) ChangedFiles
2) Deletions
3) Additions

GraphQL - changed files/deletions/additions

---

collectors/scm/bitbucket/src/main/java/com/capitalone/dashboard/collector/DefaultBitbucketCloudClient.java
collectors/scm/bitbucket/src/main/java/com/capitalone/dashboard/collector/GitCollectorTask.java
collectors/scm/bitbucket/src/main/java/com/capitalone/dashboard/model/GitRepo.java

Fix: LastUpdateTime field was changed from date to Long in this PR but was not updated uniformly across all components. This PR attempts to fix this issue. 
I am not sure why I am not able to remove white space changes from code formatting. It has to do CRLF vs LF. IntelliJ is using LF by default. To see meaningful changes please use this URL.
https://github.com/Hygieia/Hygieia/compare/master...shishirchaturvedi:address-last-update-time-field-type?expand=1&w=1
Resolves https://github.com/Hygieia/Hygieia/issues/2956 https://github.com/Hygieia/Hygieia/issues/2942
cc: @Sbrenthughes

Address last update time field type conversion error

---

api/src/main/java/com/capitalone/dashboard/config/WebSecurityConfig.java
api/src/main/java/com/capitalone/dashboard/rest/MetadataController.java
api/src/main/java/com/capitalone/dashboard/service/MetadataService.java
api/src/main/java/com/capitalone/dashboard/service/MetadataServiceImpl.java
api/src/test/java/com/capitalone/dashboard/config/TestAuthConfig.java
api/src/test/java/com/capitalone/dashboard/config/TestConfig.java
api/src/test/java/com/capitalone/dashboard/config/TestDefaultAuthConfig.java
api/src/test/java/com/capitalone/dashboard/service/MetadataServiceTest.java

supported by https://github.com/Hygieia/hygieia-core/pull/79

Added api for persisting metadata.

---

api/src/main/java/com/capitalone/dashboard/config/WebSecurityConfig.java
api/src/main/java/com/capitalone/dashboard/rest/GenericCollectorItemController.java
api/src/main/java/com/capitalone/dashboard/service/GenericCollectorItemService.java
api/src/main/java/com/capitalone/dashboard/service/GenericCollectorItemServiceImpl.java
api/src/main/java/com/capitalone/dashboard/settings/ApiSettings.java
api/src/test/java/com/capitalone/dashboard/service/GenericCollectorItemServiceImplTest.java
hygieia-jenkins-plugin/src/main/java/hygieia/builder/GenericCollectorItemBuilder.java
hygieia-jenkins-plugin/src/main/java/hygieia/builder/MetaDataBuilder.java
hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/DefaultHygieiaService.java
hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/HygieiaGlobalListener.java
hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/HygieiaPublisher.java
hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/HygieiaService.java
hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/workflow/HygieiaMetaDataPublishStep.java
hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/HygieiaPublisherTest.java
hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/workflow/HygieiaMetaDataPublishStepTest.java

Hygieia plugin - publish artifact data

Hygieia plugin - publish artifact data

---

api/src/main/java/com/capitalone/dashboard/service/BuildServiceImpl.java
hygieia-jenkins-plugin/src/main/java/hygieia/utils/HygieiaUtils.java
hygieia-jenkins-plugin/src/test/resources/json/build-stage-log-url.json
hygieia-jenkins-plugin/src/test/resources/json/build-stage.json

- Jenkins Publisher Plugin changes to support BuildStage Model changes
- API changes to support BuildStage Model changes.

Jenkins Plugin and API changes to support BuildStage

---

api-audit/pom.xml
api/pom.xml
collectors/artifact/artifactory/pom.xml
collectors/audit/nfrr/pom.xml
collectors/build/jenkins-codequality/pom.xml
collectors/cloud/cloudwatch/pom.xml
collectors/scm/github-graphql/pom.xml
hygieia-jenkins-plugin/pom.xml

Fixed the versions of core in the dependent projects where it was hardcoded to snapshot version of 3.1.1-SNAPSHOT

Fixed the versions of core in the dependent projects

---

api-audit/pom.xml
api/pom.xml
collectors/artifact/artifactory/pom.xml
collectors/audit/nfrr/pom.xml
collectors/build/jenkins-codequality/pom.xml
collectors/build/jenkins/pom.xml
collectors/build/sonar/pom.xml
collectors/cloud/cloudwatch/pom.xml
collectors/feature/gitlab/pom.xml
collectors/feature/jira/pom.xml
collectors/misc/score/pom.xml
collectors/scm/github-graphql/pom.xml
collectors/scm/github/pom.xml
collectors/scm/gitlab/pom.xml
collectors/test-results/jira-xray/pom.xml
hygieia-jenkins-plugin/pom.xml

https://github.com/Hygieia/hygieia-core/pull/90

The kernel dependency update is configured according to commit # 90 of the core

---

collectors/audit/nfrr/src/main/java/com/capitalone/dashboard/collector/AuditCollectorTask.java
collectors/audit/nfrr/src/main/java/com/capitalone/dashboard/collector/AuditCollectorUtil.java
collectors/audit/nfrr/src/test/java/com/capitalone/dashboard/collector/AuditCollectorTaskTest.java
collectors/audit/nfrr/src/test/resources/collector_items/items.json
collectors/audit/nfrr/src/test/resources/response/auditresponse.json

This PR is created to collect artifact audit result data.

NFRR artifact audit result data collection

---

api-audit/src/main/resources/logback.xml
api/src/main/resources/logback.xml
collectors/artifact/artifactory/src/main/resources/logback.xml
collectors/audit/nfrr/src/main/resources/logback.xml
collectors/build/bamboo/src/main/resources/logback.xml
collectors/build/jenkins-codequality/src/main/resources/logback.xml
collectors/build/jenkins-cucumber/src/main/resources/logback.xml
collectors/build/jenkins/src/main/resources/logback.xml
collectors/build/sonar/src/main/resources/logback.xml
collectors/cloud/aws/src/main/resources/logback.xml
collectors/cloud/cloudwatch/src/main/resources/logback.xml
collectors/cmdb/hpsm/src/main/resources/logback.xml
collectors/deploy/udeploy/src/main/resources/logback.xml
collectors/deploy/xldeploy/src/main/resources/logback.xml
collectors/feature/gitlab/src/main/resources/logback.xml
collectors/feature/jira/src/main/resources/logback.xml
collectors/feature/rally/src/main/resources/logback.xml
collectors/feature/versionone/src/main/resources/logback.xml
collectors/library-policy/nexus-iq-collector/src/main/resources/logback.xml
collectors/misc/score/src/main/resources/logback.xml
collectors/performance/appdynamics/src/main/resources/logback.xml
collectors/scm/bitbucket/src/main/resources/logback.xml
collectors/scm/github-graphql/src/main/resources/logback.xml
collectors/scm/github/src/main/resources/logback.xml
collectors/scm/gitlab/src/main/resources/logback.xml

Add thread name to logs

---

collectors/misc/score/src/main/java/com/capitalone/dashboard/ApplicationScoreService.java
collectors/misc/score/src/main/java/com/capitalone/dashboard/widget/BuildWidgetScore.java
collectors/misc/score/src/main/java/com/capitalone/dashboard/widget/DeployWidgetScore.java
collectors/misc/score/src/main/java/com/capitalone/dashboard/widget/QualityWidgetScore.java

fix #3012
This adds messages just like in the issue mentioned above.

Score detail messages

---

collectors/misc/score/src/main/java/com/capitalone/dashboard/ApplicationScoreService.java
collectors/misc/score/src/main/java/com/capitalone/dashboard/widget/GithubScmWidgetScore.java

Oops! sorry I forgot to add this change in PR 3012. 
This time the GitHub Score message is actually added.

GitHub score message

---

collectors/feature/jira/docker/properties-builder.sh

use -n and single quote make the result more correct

mac base64 more correct

---

UI/pom.xml
api-audit/pom.xml
collectors/artifact/artifactory/pom.xml
collectors/audit/nfrr/pom.xml
collectors/build/jenkins-codequality/pom.xml
collectors/cloud/cloudwatch/pom.xml
collectors/feature/gitlab/pom.xml
collectors/feature/jira/pom.xml
collectors/misc/score/pom.xml
collectors/scm/bitbucket/src/test/java/com/capitalone/dashboard/model/GitRepoTests.java
collectors/scm/github-graphql/pom.xml
collectors/scm/gitlab/pom.xml
collectors/test-results/jira-xray/pom.xml
pom.xml
travis-utilities/deploy-snapshot.sh

- Fix for Intermittent Test failures with bitbucket collector.
- Fix for snapshot deploy issues with Travis
- Incremented the version of UI to 3.0.3-SNAPSHOT
- Centralize the version of hygieia-core within Hygieia
- Incremented the javadoc version for Hygieia

Fixes for Intermittent Build Failures.

---

api-audit/src/main/java/com/capitalone/dashboard/evaluator/ArtifactEvaluator.java

Set lastupdated from created timestamp

Set lastupdated from created timestamp

---

api-audit/src/main/java/com/capitalone/dashboard/evaluator/PerformanceTestResultEvaluator.java
api-audit/src/main/java/com/capitalone/dashboard/evaluator/RegressionTestResultEvaluator.java
api-audit/src/main/java/com/capitalone/dashboard/response/PerformanceTestAuditResponse.java
api-audit/src/main/java/com/capitalone/dashboard/response/TestResultsAuditResponse.java

This PR is created to populate build artifact info in test audit response which helps to correlate test result with release build details.

Test audit response with release build artifact info

---

UI-tests/pmd.xml
UI-tests/pom.xml
UI/pom.xml
pom.xml

- Fixed issues with Maven Deploy for UI project
- Incremented the version

Fixed release issues of UI project and incremented the version

---

_data/sidebars/hygieia_sidebar.yml
index.html
pages/hygieia/collectors/artifact/artifactory.md
pages/hygieia/collectors/audit/nfrr-audit.md
pages/hygieia/collectors/build/bamboo.md
pages/hygieia/collectors/build/jenkins-codequality.md
pages/hygieia/collectors/build/jenkins-cucumber.md
pages/hygieia/collectors/build/jenkins.md
pages/hygieia/collectors/build/sonar.md
pages/hygieia/collectors/cloud/aws-cloudwatch-collector.md
pages/hygieia/collectors/cloud/aws.md
pages/hygieia/collectors/cmdb/hpsm.md
pages/hygieia/collectors/deploy/udeploy.md
pages/hygieia/collectors/deploy/xldeploy.md
pages/hygieia/collectors/feature/feature-gitlab.md
pages/hygieia/collectors/feature/jira.md
pages/hygieia/collectors/feature/rally.md
pages/hygieia/collectors/feature/versionone.md
pages/hygieia/collectors/library-policy/nexus-iq-collector.md
pages/hygieia/collectors/misc/chat-ops.md
pages/hygieia/collectors/misc/score.md
pages/hygieia/collectors/performance/appdynamics.md
pages/hygieia/collectors/scm/bitbucket.md
pages/hygieia/collectors/scm/github.md
pages/hygieia/collectors/scm/gitlab.md
pages/hygieia/collectors/scm/subversion.md
pages/hygieia/proxyauthentication.md
pages/hygieia/setup.md

Documentation updates to instruction guide (collectors, setup page, and proxy authentication).

Documentation changes for Hygieia

---

pages/hygieia/setup.md

Updates to architecture for github repos.

Changes to file architecture in setup

---

UI/src/app/dashboard/directives/widget.js

this is to address issue #3149 as a separate PR in case the referenced one is too large

ensure widgets stop collecting on destroy rather 

---

UI/src/components/widgets/team/view.js

I believe this should be 'TEAM'

TIR is not a valid CollectorType

---

pages/hygieia/collectors/build/sonar.md

Updated properties with token

---

pages/hygieia/api/api.md

Githubsync settings

---

pages/hygieia/api/api.md

Small edit to properties path in api readme.

Changes to api.properties path

---

pages/hygieia/collectors/build/sonar.md

Edited sonar.username and sonar.password to look for sonar.usernames/passwords

changes to sonar doc for usernames and passwords

---

pages/hygieia/collectors/scm/bitbucket.md

As discussed in, Hygieia/hygieia-scm-bitbucket-collector#20
I have created this pull request to update the above parameters in the application.properties of Bitbucket Cloud.
This PR closes#20

Updated git.host and git.api for configuration of Bitbucket Cloud [Documentation Update]  #3238

---

_data/sidebars/hygieia_sidebar.yml
pages/hygieia/contribute.md
pages/hygieia/newUI.md
pages/hygieia/setup.md

Documentation links and updates for CLA-Assistant and new UI.

UI Documentation changes for Contributions and Setup with new UI 

---

pages/hygieia/collectors/library-policy/whitesource.md

whitesource setup documentation

whitesource setup documentation

---

pom.xml

Upgrade org.mongodb:mongo-java-driver

Upgrade org.mongodb:mongo-java-driver from 3.0.2 to 3.12.7

---

docker-compose.yml

Signed-off-by: Gábor Lipták <gliptak@gmail.com>
```
./mvnw install -U
docker-compose up
docker-compose down
```

Add api to docker-compose

---

UI/src/components/widgets/repo/config.html
UI/src/components/widgets/repo/config.js

The repo widget is updated so that it can support the configuration of the git azure devops repositories

add repos configuration for repositories of type azure devops

---

README.md

revert readme from Hygieia/UI to hygieia/hygieia to keep banners and links

README revert 

---

pages/hygieia/architecture.md
pages/hygieia/create_widget.md
pages/hygieia/framework.md
pages/hygieia/hygieia-jenkins-plugin-alt/hygieia-jenkins-plugin-alt.md
pages/hygieia/hygieia-jenkins-plugin/hygieia-jenkins-plugin.md
pages/hygieia/screenshots.md
pages/product1/cloud_view.md
pages/product1/create_team_dashboard.md
pages/product1/dashboard_administration.md
pages/product1/keeping_score.md
pages/product1/pipeline_view.md
pages/product1/product_dashboard_intro.md
pages/product1/product_view.md
pages/product1/select_dashboard.md
pages/product1/widget_view.md

Addresses screenshot issues brought up in and closing issue #3401

Fixes broken screenshot links

---

CONTRIBUTING.md

Initial draft of contribution guidelines. Please add any comments/suggestions!

Add contributing.md first draft

---

src/app/widget_modules/infra-scan/infra-scan-config/infra-scan-config.component.html
src/app/widget_modules/infra-scan/infra-scan-config/infra-scan-config.component.ts
src/app/widget_modules/infra-scan/infra-scan-widget/infra-scan-widget.component.ts
src/karma.conf.js

Show top 5 and summary from all instanceIds, not just one

Infra widget update

---

src/app/core/navbar/navbar.component.ts

github url update
